//
// Generated by Microsoft (R) HLSL Shader Compiler 6.3.9600.16384
//
//
// Resource Bindings:
//
// Name                                 Type  Format         Dim Slot Elements
// ------------------------------ ---------- ------- ----------- ---- --------
// Linear                            sampler      NA          NA    0        1
// tex2D[7]                          texture  float4          2d   19        1
//
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_Position              0   xyzw        0      POS   float       
// TEXCOORD                 0   xy          1     NONE   float   xy  
// TEXCOORD                 1     zw        1     NONE   float     zw
// TEXCOORD                 2   xy          2     NONE   float   xy  
// TEXCOORD                 3     z         2     NONE   float     z 
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_Target                0   xyzw        0   TARGET   float   xyzw
//
ps_5_0
dcl_globalFlags refactoringAllowed | skipOptimization
dcl_sampler s0, mode_default
dcl_resource_texture2d (float,float,float,float) t19
dcl_input_ps linear v1.xy
dcl_input_ps linear v1.zw
dcl_input_ps linear v2.xy
dcl_input_ps linear v2.z
dcl_output o0.xyzw
dcl_temps 1
//
// Initial variable locations:
//   v0.x <- oPosition.x; v0.y <- oPosition.y; v0.z <- oPosition.z; v0.w <- oPosition.w; 
//   v1.x <- oTexCoord0.x; v1.y <- oTexCoord0.y; v1.z <- oTexCoord1.x; v1.w <- oTexCoord1.y; 
//   v2.x <- oTexCoord2.x; v2.y <- oTexCoord2.y; v2.z <- oVignette; 
//   o0.x <- <OCC_PS return value>.x; o0.y <- <OCC_PS return value>.y; o0.z <- <OCC_PS return value>.z; o0.w <- <OCC_PS return value>.w
//
#line 39 "\\?\C:\Users\admin\Documents\Visual Studio 2010\Projects\Vektoria_2014-12-26a\Vektoria\trunk\VektoriaApp\shaders\Source\occulus.hlsl"
sample_indexable(texture2d)(float,float,float,float) r0.x, v1.xyxx, t19.xyzw, s0
mov r0.x, r0.x  // r0.x <- R
sample_indexable(texture2d)(float,float,float,float) r0.y, v1.zwzz, t19.xyzw, s0
mov r0.y, r0.y  // r0.y <- G
sample_indexable(texture2d)(float,float,float,float) r0.z, v2.xyxx, t19.xyzw, s0
mov r0.z, r0.z  // r0.z <- B
itof r0.w, l(1)
mul o0.xyzw, r0.xyzw, v2.zzzz
ret 
// Approximately 9 instruction slots used
