//
// Generated by Microsoft (R) HLSL Shader Compiler 9.29.952.3111
//
//
// Buffer Definitions: 
//
// cbuffer TexInfo
// {
//
//   float4 f4ColorEffect;              // Offset:    0 Size:    16 [unused]
//   float fBlurStrength;               // Offset:   16 Size:     4
//   uint uBlur;                        // Offset:   20 Size:     4
//   uint uEnhancedEdges;               // Offset:   24 Size:     4
//   uint uMeanFilter;                  // Offset:   28 Size:     4
//   float fBloomOriginalIntensity;     // Offset:   32 Size:     4 [unused]
//   float fBloomIntensity;             // Offset:   36 Size:     4 [unused]
//   float fBloomOriginalSaturation;    // Offset:   40 Size:     4 [unused]
//   float fBloomSaturation;            // Offset:   44 Size:     4 [unused]
//   float fRayExposure;                // Offset:   48 Size:     4 [unused]
//   float fRayDecay;                   // Offset:   52 Size:     4 [unused]
//   float fRayDensity;                 // Offset:   56 Size:     4 [unused]
//   float fRayWeight;                  // Offset:   60 Size:     4 [unused]
//   float fTimeDelta;                  // Offset:   64 Size:     4 [unused]
//   float fBloomBlurDistance;          // Offset:   68 Size:     4 [unused]
//   float fDoFFar;                     // Offset:   72 Size:     4 [unused]
//   float fDoFNear;                    // Offset:   76 Size:     4 [unused]
//   float2 f2RayLightPos;              // Offset:   80 Size:     8 [unused]
//   float2 f2rcpFrame;                 // Offset:   88 Size:     8
//   float4 f4rcpFrameOpt;              // Offset:   96 Size:    16 [unused]
//   float4 f4DoFParams;                // Offset:  112 Size:    16 [unused]
//
// }
//
//
// Resource Bindings:
//
// Name                                 Type  Format         Dim Slot Elements
// ------------------------------ ---------- ------- ----------- ---- --------
// linearSampler                     sampler      NA          NA    1        1
// tex2D[7]                          texture  float4          2d   22        1
// TexInfo                           cbuffer      NA          NA    7        1
//
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue Format   Used
// -------------------- ----- ------ -------- -------- ------ ------
// SV_POSITION              0   xyzw        0      POS  float       
// TEXCOORD                 0   xy          1     NONE  float   xy  
// TEXCOORD                 2   xyzw        2     NONE  float       
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue Format   Used
// -------------------- ----- ------ -------- -------- ------ ------
// SV_Target                0   xyzw        0   TARGET  float   xyzw
//
ps_5_0
dcl_globalFlags refactoringAllowed
dcl_constantbuffer cb7[6], immediateIndexed
dcl_sampler s1, mode_default
dcl_resource_texture2d (float,float,float,float) t22
dcl_input_ps linear v1.xy
dcl_output o0.xyzw
dcl_temps 9
sample_indexable(texture2d)(float,float,float,float) r0.xyz, v1.xyxx, t22.xyzw, s1
ne r0.w, l(0.000000, 0.000000, 0.000000, 0.000000), cb7[5].z
if_nz r0.w
  gather4_indexable(-1,-1,0)(texture2d)(float,float,float,float) r1.xyzw, v1.xyxx, t22.xyzw, s1.w
  gather4_indexable(texture2d)(float,float,float,float) r2.xyz, v1.xyxx, t22.xyzw, s1.w
  min r0.w, r1.x, r1.z
  min r2.w, r2.z, r2.x
  min r0.w, r0.w, r2.w
  min r0.w, r0.w, r1.y
  max r2.w, r1.x, r1.z
  max r3.x, r2.z, r2.x
  max r2.w, r2.w, r3.x
  max r2.w, r1.y, r2.w
  add r0.w, -r0.w, r2.w
  mul r2.w, r2.w, l(0.166667)
  max r2.w, r2.w, l(0.041667)
  ge r2.w, r0.w, r2.w
  if_nz r2.w
    sample_l_indexable(1,-1,0)(texture2d)(float,float,float,float) r2.w, v1.xyxx, t22.xyzw, s1, l(0.000000)
    sample_l_indexable(-1,1,0)(texture2d)(float,float,float,float) r3.x, v1.xyxx, t22.wxyz, s1, l(0.000000)
    add r3.y, r1.x, r1.z
    add r3.y, r2.z, r3.y
    add r3.y, r2.x, r3.y
    mul r3.z, r3.y, l(0.250000)
    mad r3.y, r3.y, l(0.250000), -r1.y
    div r0.w, |r3.y|, r0.w
    add_sat r0.w, r0.w, l(-0.125000)
    mul r0.w, r0.w, l(1.142857)
    min r0.w, r0.w, l(0.750000)
    mad r4.xyzw, r1.zyxy, l(-2.000000, -2.000000, -2.000000, -2.000000), r1.wxwz
    add r1.w, r2.w, r4.x
    add r3.yw, r2.zzzx, r4.yyyw
    mad r1.w, |r3.y|, l(2.000000), |r1.w|
    mad r3.y, r2.x, l(-2.000000), r3.x
    add r3.y, r2.y, r3.y
    add r1.w, r1.w, |r3.y|
    add r3.x, r3.x, r4.z
    mad r3.x, |r3.w|, l(2.000000), |r3.x|
    mad r2.w, r2.z, l(-2.000000), r2.w
    add r2.y, r2.y, r2.w
    add r2.y, |r2.y|, r3.x
    ge r1.w, r2.y, r1.w
    movc r2.y, r1.w, -cb7[5].w, -cb7[5].z
    movc r1.x, r1.w, r1.z, r1.x
    movc r1.z, r1.w, r2.x, r2.z
    add r2.xz, -r1.yyyy, r1.xxzx
    add r1.xz, r1.yyyy, r1.xxzx
    mul r1.xz, r1.xxzx, l(0.500000, 0.000000, 0.500000, 0.000000)
    ge r2.w, |r2.x|, |r2.z|
    movc r1.x, r2.w, r1.x, r1.z
    max r1.z, |r2.z|, |r2.x|
    movc r2.x, r2.w, r2.y, -r2.y
    mul r2.y, r2.x, l(0.500000)
    movc r2.z, r1.w, l(0), r2.y
    and r2.y, r1.w, r2.y
    add r3.xy, r2.zyzz, v1.xyxx
    mul r1.z, r1.z, l(0.250000)
    mov r4.yz, l(0,0,0,0)
    mov r4.xw, cb7[5].zzzw
    movc r2.yz, r1.wwww, r4.xxyx, r4.zzwz
    mad r4.xyzw, r2.yzyz, l(-1.500000, -1.500000, 1.500000, 1.500000), r3.xyxy
    mov r3.xy, r4.xyxx
    mov r5.xy, r4.zwzz
    mov r5.zw, l(0,0,0,0)
    mov r2.w, l(0)
    mov r3.w, l(0)
    mov r6.x, l(0)
    loop 
      ige r6.y, r6.x, l(6)
      breakc_nz r6.y
      sample_l_indexable(texture2d)(float,float,float,float) r6.y, r3.xyxx, t22.xwyz, s1, l(0.000000)
      sample_l_indexable(texture2d)(float,float,float,float) r6.z, r5.xyxx, t22.xywz, s1, l(0.000000)
      add r6.w, -r1.x, r6.y
      ge r6.w, |r6.w|, r1.z
      add r7.x, -r1.x, r6.z
      ge r7.x, |r7.x|, r1.z
      not r7.y, r2.w
      and r7.y, r6.w, r7.y
      add r7.zw, r2.yyyz, r3.xxxy
      movc r7.yz, r7.yyyy, r7.zzwz, r3.xxyx
      not r7.w, r3.w
      and r7.w, r7.w, r7.x
      add r8.xy, -r2.yzyy, r5.xyxx
      movc r8.xy, r7.wwww, r8.xyxx, r5.xyxx
      and r7.w, r6.w, r7.x
      if_nz r7.w
        mov r3.xy, r7.yzyy
        mov r5.xy, r8.xyxx
        mov r5.zw, r6.yyyz
        break 
      endif 
      mad r8.zw, -r2.yyyz, l(0.000000, 0.000000, 2.000000, 2.000000), r7.yyyz
      movc r3.xy, r6.wwww, r7.yzyy, r8.zwzz
      mad r7.yz, r2.yyzy, l(0.000000, 2.000000, 2.000000, 0.000000), r8.xxyx
      movc r5.xy, r7.xxxx, r8.xyxx, r7.yzyy
      iadd r6.x, r6.x, l(1)
      mov r2.w, r6.w
      mov r3.w, r7.x
      mov r5.zw, r6.yyyz
    endloop 
    add r2.yz, -r3.xxyx, v1.xxyx
    movc r1.z, r1.w, r2.y, r2.z
    add r2.yz, r5.xxyx, -v1.xxyx
    movc r2.y, r1.w, r2.y, r2.z
    lt r2.z, r1.z, r2.y
    movc r2.z, r2.z, r5.z, r5.w
    add r1.y, -r1.x, r1.y
    add r1.x, -r1.x, r2.z
    lt r1.xy, r1.xyxx, l(0.000000, 0.000000, 0.000000, 0.000000)
    ieq r1.x, r1.y, r1.x
    movc r1.x, r1.x, l(0), r2.x
    add r1.y, r1.z, r2.y
    min r1.z, r1.z, r2.y
    div r1.y, l(-1.000000), r1.y
    mad r1.y, r1.z, r1.y, l(0.500000)
    mad r1.y, r0.w, l(0.125000), r1.y
    mul r1.x, r1.x, r1.y
    movc r1.y, r1.w, l(0), r1.x
    and r1.x, r1.x, r1.w
    add r2.xy, r1.yxyy, v1.xyxx
    sample_l_indexable(texture2d)(float,float,float,float) r1.xyz, r2.xyxx, t22.xyzw, s1, l(0.000000)
    dp3 r1.w, r1.xyzx, l(0.299000, 0.587000, 0.114000, 0.000000)
    add r1.w, r1.w, l(0.000000)
    mad r2.x, r3.z, r3.z, -r1.w
    mad r0.w, r0.w, r2.x, r1.w
    div r0.w, r0.w, r1.w
    min r0.w, r0.w, l(4.000000)
    mul r1.xyz, r0.wwww, r1.xyzx
  else 
    sample_l_indexable(texture2d)(float,float,float,float) r1.xyz, v1.xyxx, t22.xyzw, s1, l(0.000000)
  endif 
else 
  mov r1.xyz, r0.xyzx
endif 
if_nz cb7[1].y
  resinfo_indexable(texture2d)(float,float,float,float) r2.xy, l(0), t22.xyzw
  div r2.xy, l(1.000000, 1.000000, 1.000000, 1.000000), r2.xyxx
  mad r3.xy, r2.xyxx, cb7[1].xxxx, v1.xyxx
  mad r2.yz, -r2.yyxy, cb7[1].xxxx, v1.yyxy
  mov r3.zw, v1.yyyx
  sample_indexable(texture2d)(float,float,float,float) r4.xyz, r3.xzxx, t22.xyzw, s1
  sample_indexable(texture2d)(float,float,float,float) r5.xyz, r3.wyww, t22.xyzw, s1
  add r5.xyz, r5.xyzx, r5.xyzx
  mad r4.xyz, r4.xyzx, l(2.000000, 2.000000, 2.000000, 0.000000), r5.xyzx
  mov r2.xw, v1.yyyx
  sample_indexable(texture2d)(float,float,float,float) r5.xyz, r2.zxzz, t22.xyzw, s1
  mad r4.xyz, r5.xyzx, l(2.000000, 2.000000, 2.000000, 0.000000), r4.xyzx
  sample_indexable(texture2d)(float,float,float,float) r5.xyz, r2.wyww, t22.xyzw, s1
  mad r4.xyz, r5.xyzx, l(2.000000, 2.000000, 2.000000, 0.000000), r4.xyzx
  mad r4.xyz, r0.xyzx, l(4.000000, 4.000000, 4.000000, 0.000000), r4.xyzx
  sample_indexable(texture2d)(float,float,float,float) r5.xyz, r2.zyzz, t22.xyzw, s1
  add r4.xyz, r4.xyzx, r5.xyzx
  mov r2.xw, r3.xxxy
  sample_indexable(texture2d)(float,float,float,float) r5.xyz, r2.xyxx, t22.xyzw, s1
  add r4.xyz, r4.xyzx, r5.xyzx
  sample_indexable(texture2d)(float,float,float,float) r2.xyz, r2.zwzz, t22.xyzw, s1
  add r2.xyz, r2.xyzx, r4.xyzx
  sample_indexable(texture2d)(float,float,float,float) r3.xyz, r3.xyxx, t22.xyzw, s1
  add r2.xyz, r2.xyzx, r3.xyzx
  mad_sat r1.xyz, r2.xyzx, l(0.062500, 0.062500, 0.062500, 0.000000), r1.xyzx
endif 
if_nz cb7[1].z
  resinfo_indexable(texture2d)(float,float,float,float) r2.xy, l(0), t22.xyzw
  div r2.xy, l(1.000000, 1.000000, 1.000000, 1.000000), r2.xyxx
  add r3.xw, -r2.xxxy, v1.xxxy
  add r2.xy, r2.xyxx, v1.xyxx
  mov r2.z, v1.y
  sample_indexable(texture2d)(float,float,float,float) r4.xyz, r2.xzxx, t22.xyzw, s1
  mov r3.z, v1.y
  sample_indexable(texture2d)(float,float,float,float) r5.xyz, r3.xzxx, t22.xyzw, s1
  add r5.xyz, r5.xyzx, r5.xyzx
  mad r4.xyz, r4.xyzx, l(-2.000000, -2.000000, -2.000000, 0.000000), r5.xyzx
  sample_indexable(texture2d)(float,float,float,float) r5.xyz, r3.xwxx, t22.xyzw, s1
  add r4.xyz, r4.xyzx, r5.xyzx
  mov r3.y, r2.y
  sample_indexable(texture2d)(float,float,float,float) r6.xyz, r3.xyxx, t22.xyzw, s1
  add r4.xyz, r4.xyzx, r6.xyzx
  sample_indexable(texture2d)(float,float,float,float) r7.xyz, r2.xyxx, t22.xyzw, s1
  add r4.xyz, r4.xyzx, -r7.xyzx
  mov r3.xz, v1.xxxx
  sample_indexable(texture2d)(float,float,float,float) r8.xyz, r3.xyxx, t22.xyzw, s1
  sample_indexable(texture2d)(float,float,float,float) r3.xyz, r3.zwzz, t22.xyzw, s1
  mul r3.xyz, r3.xyzx, l(-2.000000, -2.000000, -2.000000, 0.000000)
  mad r3.xyz, r8.xyzx, l(-2.000000, -2.000000, -2.000000, 0.000000), r3.xyzx
  add r3.xyz, -r5.xyzx, r3.xyzx
  mov r2.w, r3.w
  sample_indexable(texture2d)(float,float,float,float) r2.xyz, r2.xwxx, t22.xyzw, s1
  add r2.xyz, -r2.xyzx, r3.xyzx
  add r2.xyz, r6.xyzx, r2.xyzx
  add r2.xyz, r7.xyzx, r2.xyzx
  mad r2.xyz, |r4.xyzx|, |r2.xyzx|, r1.xyzx
  mul r1.xyz, r2.xyzx, l(0.330000, 0.330000, 0.330000, 0.000000)
endif 
if_nz cb7[1].w
  resinfo_indexable(texture2d)(float,float,float,float) r2.xy, l(0), t22.xyzw
  div r2.xy, l(1.000000, 1.000000, 1.000000, 1.000000), r2.xyxx
  add r3.xy, r2.xyxx, v1.xyxx
  add r2.yz, -r2.yyxy, v1.yyxy
  mov r3.zw, v1.yyyx
  sample_indexable(texture2d)(float,float,float,float) r4.xyz, r3.xzxx, t22.xyzw, s1
  sample_indexable(texture2d)(float,float,float,float) r5.xyz, r3.wyww, t22.xyzw, s1
  add r4.xyz, r4.xyzx, r5.xyzx
  mov r2.xw, v1.yyyx
  sample_indexable(texture2d)(float,float,float,float) r5.xyz, r2.zxzz, t22.xyzw, s1
  add r4.xyz, r4.xyzx, r5.xyzx
  sample_indexable(texture2d)(float,float,float,float) r5.xyz, r2.wyww, t22.xyzw, s1
  add r4.xyz, r4.xyzx, r5.xyzx
  add r0.xyz, r0.xyzx, r4.xyzx
  sample_indexable(texture2d)(float,float,float,float) r4.xyz, r2.zyzz, t22.xyzw, s1
  add r0.xyz, r0.xyzx, r4.xyzx
  mov r2.xw, r3.xxxy
  sample_indexable(texture2d)(float,float,float,float) r4.xyz, r2.xyxx, t22.xyzw, s1
  add r0.xyz, r0.xyzx, r4.xyzx
  sample_indexable(texture2d)(float,float,float,float) r2.xyz, r2.zwzz, t22.xyzw, s1
  add r0.xyz, r0.xyzx, r2.xyzx
  sample_indexable(texture2d)(float,float,float,float) r2.xyz, r3.xyxx, t22.xyzw, s1
  add r0.xyz, r0.xyzx, r2.xyzx
  mad r0.xyz, r0.xyzx, l(0.111110, 0.111110, 0.111110, 0.000000), r1.xyzx
  mul r1.xyz, r0.xyzx, l(0.500000, 0.500000, 0.500000, 0.000000)
endif 
mov o0.xyz, r1.xyzx
mov o0.w, l(1.000000)
ret 
// Approximately 223 instruction slots used
