//
// Generated by Microsoft (R) HLSL Shader Compiler 9.29.952.3111
//
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue Format   Used
// -------------------- ----- ------ -------- -------- ------ ------
// SV_Position              0   xyzw        0      POS  float       
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue Format   Used
// -------------------- ----- ------ -------- -------- ------ ------
// no Output
ps_5_0
dcl_globalFlags refactoringAllowed

#line 42 "\\?\C:\Users\Peter\Documents\Hochschule_Kempten\Softwarepraktikum\greedyracer\source\greedyracer\Shaders\Source\shadowmap.hlsl"
ret 
// Approximately 1 instruction slots used
