//
// Generated by Microsoft (R) HLSL Shader Compiler 9.29.952.3111
//
//
//   fxc /T ps_5_0 /Zi /Od /Gfp /E ShadowMapPS /Fo
//    \\?\G:\greedyracer\source\greedyracer\Shaders\Cache\Object\Debug\ShadowMapPS.obj
//    /Fe
//    \\?\G:\greedyracer\source\greedyracer\Shaders\Cache\Error\ShadowMapPS.txt
//    /Fc
//    \\?\G:\greedyracer\source\greedyracer\Shaders\Cache\Assembly\73605c1f.asm
//    \\?\G:\greedyracer\source\greedyracer\Shaders\Source\shadowmap.hlsl
//
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue Format   Used
// -------------------- ----- ------ -------- -------- ------ ------
// SV_Position              0   xyzw        0      POS  float       
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue Format   Used
// -------------------- ----- ------ -------- -------- ------ ------
// no Output
ps_5_0
dcl_globalFlags refactoringAllowed

#line 42 "\\?\G:\greedyracer\source\greedyracer\Shaders\Source\shadowmap.hlsl"
ret 
// Approximately 1 instruction slots used
