//
// Generated by Microsoft (R) HLSL Shader Compiler 9.29.952.3111
//
//
// Buffer Definitions: 
//
// cbuffer TexInfo
// {
//
//   float4 f4ColorEffect;              // Offset:    0 Size:    16 [unused]
//   float fBlurStrength;               // Offset:   16 Size:     4 [unused]
//   uint uBlur;                        // Offset:   20 Size:     4 [unused]
//   uint uEnhancedEdges;               // Offset:   24 Size:     4 [unused]
//   uint uMeanFilter;                  // Offset:   28 Size:     4 [unused]
//   float fBloomOriginalIntensity;     // Offset:   32 Size:     4 [unused]
//   float fBloomIntensity;             // Offset:   36 Size:     4 [unused]
//   float fBloomOriginalSaturation;    // Offset:   40 Size:     4 [unused]
//   float fBloomSaturation;            // Offset:   44 Size:     4 [unused]
//   float fRayExposure;                // Offset:   48 Size:     4 [unused]
//   float fRayDecay;                   // Offset:   52 Size:     4 [unused]
//   float fRayDensity;                 // Offset:   56 Size:     4 [unused]
//   float fRayWeight;                  // Offset:   60 Size:     4 [unused]
//   float fTimeDelta;                  // Offset:   64 Size:     4 [unused]
//   float fBloomBlurDistance;          // Offset:   68 Size:     4 [unused]
//   float fDoFFar;                     // Offset:   72 Size:     4
//   float fDoFNear;                    // Offset:   76 Size:     4
//   float2 f2RayLightPos;              // Offset:   80 Size:     8 [unused]
//   float2 f2rcpFrame;                 // Offset:   88 Size:     8 [unused]
//   float4 f4rcpFrameOpt;              // Offset:   96 Size:    16 [unused]
//   float4 f4DoFParams;                // Offset:  112 Size:    16 [unused]
//
// }
//
//
// Resource Bindings:
//
// Name                                 Type  Format         Dim Slot Elements
// ------------------------------ ---------- ------- ----------- ---- --------
// transparentDepthTex               texture   float          2d   22        1
// opaqueDepthTex                    texture   float          2d   23        1
// TexInfo                           cbuffer      NA          NA    7        1
//
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue Format   Used
// -------------------- ----- ------ -------- -------- ------ ------
// SV_POSITION              0   xyzw        0      POS  float   xy  
// TEXCOORD                 0   xy          1     NONE  float       
// TEXCOORD                 2   xyzw        2     NONE  float       
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue Format   Used
// -------------------- ----- ------ -------- -------- ------ ------
// SV_TARGET                0   xyzw        0   TARGET  float   xyzw
//
ps_5_0
dcl_globalFlags refactoringAllowed
dcl_constantbuffer cb7[5], immediateIndexed
dcl_resource_texture2d (float,float,float,float) t22
dcl_resource_texture2d (float,float,float,float) t23
dcl_input_ps_siv linear noperspective v0.xy, position
dcl_output o0.xyzw
dcl_temps 2

#line 82 "\\?\C:\Users\admin\Documents\Visual Studio 2010\Projects\Vektoria_2015-02-12a\Vektoria\trunk\VektoriaApp\shaders\source\depthoffield.hlsl"
nop 
ftoi r0.xy, v0.xyxx
mov r0.zw, l(0,0,0,0)
ld_indexable(texture2d)(float,float,float,float) r0.x, r0.xyzw, t23.xyzw
mov r0.x, r0.x  // fZBufferDepth<0:Inf>

#line 75
mov r0.y, -cb7[4].w
add r0.x, r0.y, r0.x
div r0.x, cb7[4].z, r0.x  // LinearDepth<0:NaN:Inf>

#line 82
mov r0.x, r0.x  // fOpaqueDepth<0:NaN:Inf>
nop 
ftoi r1.xy, v0.xyxx
mov r1.zw, l(0,0,0,0)
ld_indexable(texture2d)(float,float,float,float) r0.z, r1.xyzw, t22.yzxw
mov r0.z, r0.z  // fZBufferDepth<0:Inf>

#line 75
add r0.y, r0.y, r0.z
div r0.y, cb7[4].z, r0.y  // LinearDepth<0:NaN:Inf>

#line 83
mov r0.y, r0.y  // fTransparentDepth<0:NaN:Inf>

#line 89
lt r0.z, r0.x, r0.y
movc r0.x, r0.z, r0.x, r0.y  // fDepth<0:NaN:Inf>
mov r0.x, -r0.x
add r0.x, r0.x, l(1.000000)  // fDepth<0:NaN:Inf>
nop 
mov r0.z, r0.x  // fDepth<0:NaN:Inf>

#line 65
add r0.w, r0.z, l(-0.003000)
div r0.w, r0.w, l(0.003000)
max r0.w, r0.w, l(0.000000)
min r0.w, r0.w, l(1.000000)
mov r0.w, -r0.w
add r0.w, r0.w, l(1.000000)  // f0<0:[0f,1f]>
add r0.z, r0.z, l(-0.001000)
div r0.z, r0.z, l(0.079000)
max r0.z, r0.z, l(0.000000)
min r0.z, r0.z, l(1.000000)  // f1<0:[0f,1f]>
add r0.z, r0.z, r0.w
max r0.z, r0.z, l(0.000000)
min r0.y, r0.z, l(1.000000)  // fBlur<0:[0f,1f]>
mov r0.y, r0.y  // BlurFactor<0:[0f,1f]>

#line 93
mov r0.y, r0.y  // fBlur<0:[0f,1f]>
mov o0.zw, l(0,0,1.000000,1.000000)  // PS_DepthBlurGeneration<2: 1f,3: 1f>
mov o0.xy, r0.xyxx  // PS_DepthBlurGeneration<0:NaN:Inf,1:[0f,1f]>
ret 
// Approximately 41 instruction slots used
