//
// Generated by Microsoft (R) HLSL Shader Compiler 9.29.952.3111
//
//
// Buffer Definitions: 
//
// cbuffer TexInfo
// {
//
//   float4 f4ColorAmbient;             // Offset:    0 Size:    16 [unused]
//   float fA;                          // Offset:   16 Size:     4 [unused]
//   float fH;                          // Offset:   20 Size:     4 [unused]
//   float fBumpStrength;               // Offset:   24 Size:     4
//   float frTransparency;              // Offset:   28 Size:     4 [unused]
//   float4 f4ColorSSS;                 // Offset:   32 Size:    16 [unused]
//   float4 f4SSSBRDFParams;            // Offset:   48 Size:    16 [unused]
//   uint uImage;                       // Offset:   64 Size:     4 [unused]
//   uint uGlow;                        // Offset:   68 Size:     4 [unused]
//   uint uSpecular;                    // Offset:   72 Size:     4 [unused]
//   uint uBump;                        // Offset:   76 Size:     4
//   uint uImageBlack;                  // Offset:   80 Size:     4 [unused]
//   uint uGlowAsImage;                 // Offset:   84 Size:     4 [unused]
//   uint uSpecularAsImage;             // Offset:   88 Size:     4 [unused]
//   uint uHeightAsImage;               // Offset:   92 Size:     4 [unused]
//   uint uImageWhite;                  // Offset:   96 Size:     4 [unused]
//   uint uGlowWhite;                   // Offset:  100 Size:     4 [unused]
//   uint uSpecularWhite;               // Offset:  104 Size:     4 [unused]
//   uint uHeight;                      // Offset:  108 Size:     4 [unused]
//   uint uShadingOn;                   // Offset:  112 Size:     4 [unused]
//   uint uGlowAsAmbient;               // Offset:  116 Size:     4 [unused]
//   uint uChromaKeying;                // Offset:  120 Size:     4 [unused]
//   uint uEnvironment;                 // Offset:  124 Size:     4 [unused]
//   uint uPOM;                         // Offset:  128 Size:     4 [unused]
//   uint uTexBRDF;                     // Offset:  132 Size:     4 [unused]
//   uint uTexSSS;                      // Offset:  136 Size:     4 [unused]
//   uint uReflectionMap;               // Offset:  140 Size:     4 [unused]
//   uint uixPos;                       // Offset:  144 Size:     4 [unused]
//   uint uiyPos;                       // Offset:  148 Size:     4 [unused]
//   uint uixPics;                      // Offset:  152 Size:     4 [unused]
//   uint uiyPics;                      // Offset:  156 Size:     4 [unused]
//   float fSpecularRoughness;          // Offset:  160 Size:     4 [unused]
//   float fSpecularIOR;                // Offset:  164 Size:     4 [unused]
//   uint uPad1;                        // Offset:  168 Size:     4 [unused]
//   uint uPad2;                        // Offset:  172 Size:     4 [unused]
//
// }
//
//
// Resource Bindings:
//
// Name                                 Type  Format         Dim Slot Elements
// ------------------------------ ---------- ------- ----------- ---- --------
// g_Sampler                         sampler      NA          NA    0        1
// tex2D[0]                          texture  float4          2d   15        1
// tex2D[3]                          texture  float4          2d   18        1
// TexInfo                           cbuffer      NA          NA    5        1
//
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue Format   Used
// -------------------- ----- ------ -------- -------- ------ ------
// NORMAL                   0   xyz         0     NONE  float   xyz 
// TEXCOORD                 0   xy          1     NONE  float   xy  
// TEXCOORD                 1   xyz         2     NONE  float       
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue Format   Used
// -------------------- ----- ------ -------- -------- ------ ------
// SV_TARGET                0   xyzw        0   TARGET  float   xyzw
// SV_TARGET                1   xyzw        1   TARGET  float   xyzw
//
ps_5_0
dcl_globalFlags refactoringAllowed
dcl_constantbuffer cb5[5], immediateIndexed
dcl_sampler s0, mode_default
dcl_resource_texture2d (float,float,float,float) t15
dcl_resource_texture2d (float,float,float,float) t18
dcl_input_ps linear v0.xyz
dcl_input_ps linear v1.xy
dcl_output o0.xyzw
dcl_output o1.xyzw
dcl_temps 4

#line 61 "\\?\C:\Users\admin\Documents\Visual Studio 2010\Projects\Vektoria_2015-02-12a\Vektoria\trunk\VektoriaApp\shaders\source\reflectiveshadowmaps.hlsl"
dp3 r0.x, v0.xyzx, v0.xyzx
rsq r0.x, r0.x
mul r0.yzw, r0.xxxx, v0.zzxy  // f3N<2:NaN:Inf,0:NaN:Inf,1:NaN:Inf>
mul r1.xyz, r0.wyzw, l(1.000000, 0.000000, 0.000000, 0.000000)
mul r2.xyz, r0.yzwy, l(0.000000, 1.000000, 0.000000, 0.000000)
mov r2.xyz, -r2.xyzx
add r1.xyz, r1.xyzx, r2.xyzx  // f3C1<0:NaN:Inf,1:NaN:Inf,2: 0f>
mul r2.xyz, r0.wyzw, l(0.000000, 0.000000, 1.000000, 0.000000)
mul r3.xyz, r0.yzwy, l(1.000000, 0.000000, 0.000000, 0.000000)
mov r3.xyz, -r3.xyzx
add r2.xyz, r2.xyzx, r3.xyzx  // f3C2<0:NaN:Inf,1: 0f,2:NaN:Inf>

#line 67
dp3 r1.w, r1.xyzx, r1.xyzx
sqrt r1.w, r1.w
dp3 r2.w, r2.xyzx, r2.xyzx
sqrt r2.w, r2.w
lt r1.w, r2.w, r1.w
if_nz r1.w
  mov r2.xyz, r1.xyzx  // f3T<0:NaN:Inf,1:NaN:Inf,2: 0f>
else 

#line 73
  mov r2.xyz, r2.xyzx  // f3T<0:NaN:Inf,1: 0f,2:NaN:Inf>

#line 67
endif 

#line 75
mul r1.xyz, r0.wyzw, r2.zxyz
mul r0.yzw, r0.yyzw, r2.yyzx
mov r0.yzw, -r0.yyzw
add r0.yzw, r0.yyzw, r1.xxyz
mov r0.yzw, -r0.yyzw
dp3 r1.x, r0.yzwy, r0.yzwy
rsq r1.x, r1.x
mul r0.yzw, r0.yyzw, r1.xxxx  // f3B<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf>

#line 78
ine r1.x, l(0, 0, 0, 0), cb5[4].w
if_nz r1.x
  sample_indexable(texture2d)(float,float,float,float) r1.xy, v1.xyxx, t18.xyzw, s0
  mul r1.xy, r1.xyxx, l(2.000000, 2.000000, 0.000000, 0.000000)
  add r1.xy, r1.xyxx, l(-1.000000, -1.000000, 0.000000, 0.000000)  // f3BumpNormal<0:Inf,1:Inf>
  mul r1.xy, r1.xyxx, cb5[1].zzzz  // f3BumpNormal<0:NaN:Inf,1:NaN:Inf>
  mul r1.xzw, r2.xxyz, r1.xxxx
  mul r0.yzw, r0.yyzw, r1.yyyy
  add r0.yzw, r0.yyzw, r1.xxzw
  add r0.yzw, r0.yyzw, v0.xxyz  // input<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf>
  dp3 r1.x, r0.yzwy, r0.yzwy
  rsq r1.x, r1.x
  mul r0.yzw, r0.yyzw, r1.xxxx  // output<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf>

#line 78
else 

#line 87
  mul r1.xyz, r0.xxxx, v0.xyzx
  add r1.xyz, r1.xyzx, l(1.000000, 1.000000, 1.000000, 0.000000)
  mul r1.xyz, r1.xyzx, l(0.500000, 0.500000, 0.500000, 0.000000)
  dp3 r0.x, r1.xyzx, r1.xyzx
  rsq r0.x, r0.x
  mul r0.yzw, r0.xxxx, r1.xxyz  // output<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf>

#line 78
endif 

#line 90
sample_indexable(texture2d)(float,float,float,float) r1.xyz, v1.xyxx, t15.xyzw, s0
mov r1.xyz, r1.xyzx  // output<4:Inf,5:Inf,6:Inf>

#line 93
mov o0.xyz, r0.yzwy  // RSMPS<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf>
mov o0.w, l(0)  // RSMPS<3: 0f>
mov o1.xyz, r1.xyzx  // RSMPS<4:Inf,5:Inf,6:Inf>
mov o1.w, l(1.000000)  // RSMPS<7: 1f>
ret 
// Approximately 57 instruction slots used
