//
// Generated by Microsoft (R) HLSL Shader Compiler 9.29.952.3111
//
//
// Buffer Definitions: 
//
// cbuffer cbPerObject
// {
//
//   float4x4 g_mWorld;                 // Offset:    0 Size:    64
//
// }
//
// cbuffer cbPerCamera
// {
//
//   float4x4 g_mViewProj;              // Offset:    0 Size:    64
//
// }
//
//
// Resource Bindings:
//
// Name                                 Type  Format         Dim Slot Elements
// ------------------------------ ---------- ------- ----------- ---- --------
// cbPerObject                       cbuffer      NA          NA    0        1
// cbPerCamera                       cbuffer      NA          NA    1        1
//
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue Format   Used
// -------------------- ----- ------ -------- -------- ------ ------
// POSITION                 0   xyzw        0     NONE  float   xyzw
// NORMAL                   0   xyz         1     NONE  float   xyz 
// TEXCOORD                 0   xy          2     NONE  float   xy  
// TANGENT                  0   xyz         3     NONE  float       
// BITANGENT                0   xyz         4     NONE  float       
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue Format   Used
// -------------------- ----- ------ -------- -------- ------ ------
// NORMAL                   0   xyz         0     NONE  float   xyz 
// TEXCOORD                 0   xy          1     NONE  float   xy  
// TEXCOORD                 1   xyz         2     NONE  float   xyz 
// SV_POSITION              0   xyzw        3      POS  float   xyzw
//
vs_5_0
dcl_globalFlags refactoringAllowed
dcl_constantbuffer cb0[4], immediateIndexed
dcl_constantbuffer cb1[4], immediateIndexed
dcl_input v0.xyzw
dcl_input v1.xyz
dcl_input v2.xy
dcl_output o0.xyz
dcl_output o1.xy
dcl_output o2.xyz
dcl_output_siv o3.xyzw, position
dcl_temps 4

#line 45 "\\?\C:\Users\admin\Documents\Visual Studio 2010\Projects\Vektoria_2015-02-12a\Vektoria\trunk\VektoriaApp\shaders\source\reflectiveshadowmaps.hlsl"
dp4 r0.x, v0.xyzw, cb0[0].xyzw  // f4WorldPos<0:NaN:Inf>
dp4 r0.y, v0.xyzw, cb0[1].xyzw  // f4WorldPos<1:NaN:Inf>
dp4 r0.z, v0.xyzw, cb0[2].xyzw  // f4WorldPos<2:NaN:Inf>
dp4 r0.w, v0.xyzw, cb0[3].xyzw  // f4WorldPos<3:NaN:Inf>
mov r1.x, r0.x  // f4WorldPos<0:NaN:Inf>
mov r1.y, r0.y  // f4WorldPos<1:NaN:Inf>
mov r1.z, r0.z  // f4WorldPos<2:NaN:Inf>
mov r1.xyz, r1.xyzx  // output<5:NaN:Inf,6:NaN:Inf,7:NaN:Inf>
dp4 r2.x, r0.xyzw, cb1[0].xyzw  // output<8:NaN:Inf>
dp4 r2.y, r0.xyzw, cb1[1].xyzw  // output<9:NaN:Inf>
dp4 r2.z, r0.xyzw, cb1[2].xyzw  // output<10:NaN:Inf>
dp4 r2.w, r0.xyzw, cb1[3].xyzw  // output<11:NaN:Inf>
dp3 r0.x, v1.xyzx, cb0[0].xyzx  // output<0:NaN:Inf>
dp3 r0.y, v1.xyzx, cb0[1].xyzx  // output<1:NaN:Inf>
dp3 r0.z, v1.xyzx, cb0[2].xyzx  // output<2:NaN:Inf>
mov r3.xy, v2.xyxx  // output<3,4>
mov o3.xyzw, r2.xyzw  // RSMVS<8:NaN:Inf,9:NaN:Inf,10:NaN:Inf,11:NaN:Inf>
mov o0.xyz, r0.xyzx  // RSMVS<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf>
mov o2.xyz, r1.xyzx  // RSMVS<5:NaN:Inf,6:NaN:Inf,7:NaN:Inf>
mov o1.xy, r3.xyxx  // RSMVS<3,4>
ret 
// Approximately 21 instruction slots used
