//
// Generated by Microsoft (R) HLSL Shader Compiler 9.29.952.3111
//
//
// Resource Bindings:
//
// Name                                 Type  Format         Dim Slot Elements
// ------------------------------ ---------- ------- ----------- ---- --------
// linearSampler                     sampler      NA          NA    1        1
// tex2D[7]                          texture  float4          2d   22        1
// tex2D[8]                          texture  float4          2d   23        1
// depthTex                          texture   float       2dMS4   24        1
// lumTex                            texture  float4          2d   25        1
//
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue Format   Used
// -------------------- ----- ------ -------- -------- ------ ------
// SV_POSITION              0   xyzw        0      POS  float   xy  
// TEXCOORD                 0   xy          1     NONE  float   xy  
// TEXCOORD                 2   xyzw        2     NONE  float       
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue Format   Used
// -------------------- ----- ------ -------- -------- ------ ------
// SV_TARGET                0   xyzw        0   TARGET  float   xyzw
//
ps_5_0
dcl_globalFlags refactoringAllowed
dcl_sampler s1, mode_default
dcl_resource_texture2d (float,float,float,float) t22
dcl_resource_texture2d (float,float,float,float) t23
dcl_resource_texture2dms(4) (float,float,float,float) t24
dcl_resource_texture2d (float,float,float,float) t25
dcl_input_ps_siv linear noperspective v0.xy, position
dcl_input_ps linear v1.xy
dcl_output o0.xyzw
dcl_temps 4

#line 127 "\\?\C:\Users\admin\Documents\Visual Studio 2010\Projects\Vektoria_2015-02-12a\Vektoria\trunk\VektoriaApp\shaders\source\BloomPost.hlsl"
ftoi r0.xy, v0.xyxx
mov r0.zw, l(0,0,0,0)
ldms_indexable(texture2dms)(float,float,float,float) r0.x, r0.xyzw, t24.xyzw, l(0)
mov r0.x, r0.x  // fDepth<0:Inf>
mul r0.x, r0.x, l(3.000000)
mul r0.x, r0.x, l(1.300000)  // fBloomIntesity<0:Inf>
sample_indexable(texture2d)(float,float,float,float) r0.yzw, v1.xyxx, t23.wxyz, s1
mov r0.yzw, r0.yyzw  // f3BloomColor<0:Inf,1:Inf,2:Inf>
sample_indexable(texture2d)(float,float,float,float) r1.xyz, v1.xyxx, t22.xyzw, s1
mov r1.xyz, r1.xyzx  // f3OriginalColor<0:Inf,1:Inf,2:Inf>
nop 
mov r2.xy, v1.xyxx  // f2TexCoord<0,1>

#line 44 "postconstants.h"
sample_l_indexable(texture2d)(float,float,float,float) r1.w, r2.xyxx, t25.yzwx, s1, l(10.000000)
mul r1.w, r1.w, l(1.442695)
exp r1.w, r1.w  // GetAvgLuminance<0:Inf:[0f,1.#INFf]>

#line 133 "\\?\C:\Users\admin\Documents\Visual Studio 2010\Projects\Vektoria_2015-02-12a\Vektoria\trunk\VektoriaApp\shaders\source\BloomPost.hlsl"
mov r1.w, r1.w  // fAvgLuminance<0:Inf:[0f,1.#INFf]>
nop 
mov r1.xyz, r1.xyzx  // f3Color<0:Inf,1:Inf,2:Inf>
mov r1.w, r1.w  // fAvgLuminance<0:Inf:[0f,1.#INFf]>

#line 78 "postconstants.h"
nop 
nop 
mov r1.xyz, r1.xyzx  // f3Color<0:Inf,1:Inf,2:Inf>
mov r1.w, r1.w  // fAvgLuminance<0:Inf:[0f,1.#INFf]>

#line 67
max r1.w, r1.w, l(0.000100)  // fAvgLuminance<0:Inf:[0.0001f,1.#INFf]>
div r1.w, l(1.000000), r1.w  // fLinearExposure<0:[0f,10000f]>
max r1.w, r1.w, l(0.000100)
log r1.w, r1.w  // fExposure<0:[-13.2877f,13.2877f]>
add r1.w, r1.w, l(-0.000000)  // fExposure<0:[-13.2877f,13.2877f]>
exp r1.w, r1.w
mul r1.xyz, r1.xyzx, r1.wwww  // CalcExposedColor<0:Inf,1:Inf,2:Inf>

#line 80
mov r1.xyz, r1.xyzx  // f3Color<0:Inf,1:Inf,2:Inf>
nop 
mov r1.xyz, r1.xyzx  // f3Color<0:Inf,1:Inf,2:Inf>

#line 50
add r1.xyz, r1.xyzx, l(-0.004000, -0.004000, -0.004000, 0.000000)
max r1.xyz, r1.xyzx, l(0.000000, 0.000000, 0.000000, 0.000000)  // f3Color<0:Inf:[-0f,1.#INFf],1:Inf:[-0f,1.#INFf],2:Inf:[-0f,1.#INFf]>
mul r2.xyz, r1.xyzx, l(6.200000, 6.200000, 6.200000, 0.000000)
add r3.xyz, r2.xyzx, l(0.500000, 0.500000, 0.500000, 0.000000)
mul r3.xyz, r1.xyzx, r3.xyzx
add r2.xyz, r2.xyzx, l(1.700000, 1.700000, 1.700000, 0.000000)
mul r1.xyz, r1.xyzx, r2.xyzx
add r1.xyz, r1.xyzx, l(0.060000, 0.060000, 0.060000, 0.000000)
div r1.xyz, r3.xyzx, r1.xyzx  // f3Color<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf>

#line 54
log r1.xyz, r1.xyzx
mul r1.xyz, r1.xyzx, l(2.200000, 2.200000, 2.200000, 0.000000)
exp r1.xyz, r1.xyzx  // ToneMapFilmicALU<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf>

#line 81
mov r1.xyz, r1.xyzx  // f3Color<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf>
mov r1.xyz, r1.xyzx  // ToneMap<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf>

#line 135 "\\?\C:\Users\admin\Documents\Visual Studio 2010\Projects\Vektoria_2015-02-12a\Vektoria\trunk\VektoriaApp\shaders\source\BloomPost.hlsl"
mov r1.xyz, r1.xyzx  // f3OriginalColor<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf>
mul r0.xyz, r0.xxxx, r0.yzwy  // f3BloomColor<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf>
add r0.xyz, r0.xyzx, r1.xyzx  // f3ColorOut<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf>
mov o0.xyz, r0.xyzx  // PS_BLOOMACCUM<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf>
mov o0.w, l(1.000000)  // PS_BLOOMACCUM<3: 1f>
ret 
// Approximately 53 instruction slots used
