//
// Generated by Microsoft (R) HLSL Shader Compiler 9.29.952.3111
//
//
// Resource Bindings:
//
// Name                                 Type  Format         Dim Slot Elements
// ------------------------------ ---------- ------- ----------- ---- --------
// linearSampler                     sampler      NA          NA    1        1
// tex2D[7]                          texture  float4          2d   22        1
//
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue Format   Used
// -------------------- ----- ------ -------- -------- ------ ------
// SV_POSITION              0   xyzw        0      POS  float       
// TEXCOORD                 0   xy          1     NONE  float   xy  
// TEXCOORD                 2   xyzw        2     NONE  float       
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue Format   Used
// -------------------- ----- ------ -------- -------- ------ ------
// SV_TARGET                0   xyzw        0   TARGET  float   xyzw
//
ps_5_0
dcl_globalFlags refactoringAllowed
dcl_sampler s1, mode_default
dcl_resource_texture2d (float,float,float,float) t22
dcl_input_ps linear v1.xy
dcl_output o0.xyzw
dcl_temps 1

#line 100 "\\?\C:\Users\admin\Documents\Visual Studio 2010\Projects\Vektoria_2015-02-12a\Vektoria\trunk\VektoriaApp\shaders\source\BloomPost.hlsl"
sample_indexable(texture2d)(float,float,float,float) r0.xyz, v1.xyxx, t22.xyzw, s1
mov r0.xyz, r0.xyzx  // f3Color<0:Inf,1:Inf,2:Inf>
nop 
mov r0.xyz, r0.xyzx  // f3Color<0:Inf,1:Inf,2:Inf>

#line 39 "postconstants.h"
dp3 r0.x, r0.xyzx, l(0.299000, 0.587000, 0.114000, 0.000000)
max r0.x, r0.x, l(0.000100)  // CalcLuminance<0:Inf:[0.0001f,1.#INFf]>

#line 102 "\\?\C:\Users\admin\Documents\Visual Studio 2010\Projects\Vektoria_2015-02-12a\Vektoria\trunk\VektoriaApp\shaders\source\BloomPost.hlsl"
mov r0.x, r0.x  // fLuminance<0:Inf:[0.0001f,1.#INFf]>
mov o0.x, r0.x  // PS_LUMINANCE<0:Inf:[0.0001f,1.#INFf]>
mov o0.yzw, l(0,1.000000,1.000000,1.000000)  // PS_LUMINANCE<1: 1f,2: 1f,3: 1f>
ret 
// Approximately 10 instruction slots used
