//
// Generated by Microsoft (R) HLSL Shader Compiler 9.29.952.3111
//
//
// Buffer Definitions: 
//
// cbuffer TexInfo
// {
//
//   float4 f4ColorAmbient;             // Offset:    0 Size:    16
//   float fA;                          // Offset:   16 Size:     4
//   float fH;                          // Offset:   20 Size:     4
//   float fBumpStrength;               // Offset:   24 Size:     4
//   float frTransparency;              // Offset:   28 Size:     4
//   float4 f4ColorSSS;                 // Offset:   32 Size:    16
//   float4 f4SSSBRDFParams;            // Offset:   48 Size:    16
//   uint uImage;                       // Offset:   64 Size:     4
//   uint uGlow;                        // Offset:   68 Size:     4
//   uint uSpecular;                    // Offset:   72 Size:     4
//   uint uBump;                        // Offset:   76 Size:     4
//   uint uImageBlack;                  // Offset:   80 Size:     4
//   uint uGlowAsImage;                 // Offset:   84 Size:     4
//   uint uSpecularAsImage;             // Offset:   88 Size:     4
//   uint uHeightAsImage;               // Offset:   92 Size:     4 [unused]
//   uint uImageWhite;                  // Offset:   96 Size:     4 [unused]
//   uint uGlowWhite;                   // Offset:  100 Size:     4 [unused]
//   uint uSpecularWhite;               // Offset:  104 Size:     4
//   uint uHeight;                      // Offset:  108 Size:     4 [unused]
//   uint uShadingOn;                   // Offset:  112 Size:     4
//   uint uGlowAsAmbient;               // Offset:  116 Size:     4
//   uint uChromaKeying;                // Offset:  120 Size:     4
//   uint uEnvironment;                 // Offset:  124 Size:     4
//   uint uPOM;                         // Offset:  128 Size:     4
//   uint uTexBRDF;                     // Offset:  132 Size:     4
//   uint uTexSSS;                      // Offset:  136 Size:     4
//   uint uReflectionMap;               // Offset:  140 Size:     4
//   uint uixPos;                       // Offset:  144 Size:     4
//   uint uiyPos;                       // Offset:  148 Size:     4
//   uint uixPics;                      // Offset:  152 Size:     4
//   uint uiyPics;                      // Offset:  156 Size:     4
//
// }
//
// cbuffer ViewportArt
// {
//
//   float4 f4ColorViewportOutline;     // Offset:    0 Size:    16
//   float4 f4FogParams;                // Offset:   16 Size:    16
//   float4x4 mColorModification;       // Offset:   32 Size:    64
//   uint uStyleColor;                  // Offset:   96 Size:     4
//   uint uStyleHalfTransparent;        // Offset:  100 Size:     4
//   uint uStylePopart;                 // Offset:  104 Size:     4 [unused]
//   uint uStyleOutlining;              // Offset:  108 Size:     4
//   uint uStyleMonochrome;             // Offset:  112 Size:     4 [unused]
//   uint uStyleOwn;                    // Offset:  116 Size:     4 [unused]
//   uint uStyleFog;                    // Offset:  120 Size:     4
//   uint uPad0;                        // Offset:  124 Size:     4 [unused]
//
// }
//
//
// Resource Bindings:
//
// Name                                 Type  Format         Dim Slot Elements
// ------------------------------ ---------- ------- ----------- ---- --------
// linearSampler                     sampler      NA          NA    0        1
// shadowSampler                   sampler_c      NA          NA    2        1
// shadowMap                         texture  float4          2d   11        1
// tex2D[0]                          texture  float4          2d   15        1
// tex2D[1]                          texture  float4          2d   16        1
// tex2D[2]                          texture  float4          2d   17        1
// tex2D[3]                          texture  float4          2d   18        1
// tex2D[4]                          texture  float4          2d   19        1
// tex2D[5]                          texture  float4          2d   20        1
// tex2D[6]                          texture  float4          2d   21        1
// TexInfo                           cbuffer      NA          NA    1        1
// ViewportArt                       cbuffer      NA          NA    2        1
//
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue Format   Used
// -------------------- ----- ------ -------- -------- ------ ------
// SV_POSITION              0   xyzw        0      POS  float       
// NORMAL                   0   xyz         1     NONE  float   xyz 
// LIGHTS                   5      w        1     NONE  float      w
// TANGENT                  0   xyz         2     NONE  float   xyz 
// LIGHTS                  16      w        2     NONE  float      w
// BITANGENT                0   xyz         3     NONE  float   xyz 
// LIGHTS                  17      w        3     NONE  float      w
// TEXCOORD                 0   xy          4     NONE  float   xy  
// LIGHTS                   4     zw        4     NONE  float     zw
// TEXCOORD                 1   xyz         5     NONE  float   xyz 
// LIGHTS                  29      w        5     NONE  float      w
// TEXCOORD                 2   xyzw        6     NONE  float   xyzw
// LIGHTS                   0   xyzw        7     NONE  float   xyzw
// LIGHTS                   2   xyzw        8     NONE  float   xyz 
// LIGHTS                   3   xyzw        9     NONE  float   xyzw
// LIGHTS                   6   xyzw       10     NONE   uint   xyz 
// LIGHTS                  10   xyzw       11     NONE   uint   xyzw
// LIGHTS                  11   xyzw       12     NONE  float   xyzw
// LIGHTS                  12   xyzw       13     NONE  float   xyzw
// LIGHTS                  14   xyzw       14     NONE  float   xyz 
// LIGHTS                  15   xyzw       15     NONE  float   xyzw
// LIGHTS                  21   xyzw       16     NONE   uint    yzw
// LIGHTS                  23   xyzw       17     NONE  float   xyzw
// LIGHTS                  24   xyzw       18     NONE  float   xyzw
// LIGHTS                  26   xyzw       19     NONE  float   xyz 
// LIGHTS                  27   xyz        20     NONE  float   xyz 
// LIGHTS                  32   xyzw       21     NONE   uint   x zw
// LIGHTS                  35   xyzw       22     NONE  float   xyzw
// LIGHTS                  36   xyzw       23     NONE  float   xyzw
// LIGHTS                  38   xyzw       24     NONE  float   xyz 
// LIGHTS                  39   xyz        25     NONE  float   xyz 
// LIGHTS                  43   xyzw       26     NONE   uint   xy w
// LIGHTS                  47   xyzw       27     NONE  float   xyzw
// COUNT                    0   x          28     NONE   uint   x   
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue Format   Used
// -------------------- ----- ------ -------- -------- ------ ------
// SV_Target                0   xyzw        0   TARGET  float   xyzw
//
ps_5_0
dcl_globalFlags refactoringAllowed
dcl_constantbuffer cb1[10], immediateIndexed
dcl_constantbuffer cb2[8], immediateIndexed
dcl_sampler s0, mode_default
dcl_sampler s2, mode_comparison
dcl_resource_texture2d (float,float,float,float) t11
dcl_resource_texture2d (float,float,float,float) t15
dcl_resource_texture2d (float,float,float,float) t16
dcl_resource_texture2d (float,float,float,float) t17
dcl_resource_texture2d (float,float,float,float) t18
dcl_resource_texture2d (float,float,float,float) t19
dcl_resource_texture2d (float,float,float,float) t20
dcl_resource_texture2d (float,float,float,float) t21
dcl_input_ps linear v1.xyz
dcl_input_ps linear v1.w
dcl_input_ps linear v2.xyz
dcl_input_ps linear v2.w
dcl_input_ps linear v3.xyz
dcl_input_ps linear v3.w
dcl_input_ps linear v4.xy
dcl_input_ps linear v4.zw
dcl_input_ps linear v5.xyz
dcl_input_ps linear v5.w
dcl_input_ps linear v6.xyzw
dcl_input_ps linear v7.xyzw
dcl_input_ps linear v8.xyz
dcl_input_ps linear v9.xyzw
dcl_input_ps constant v10.xyz
dcl_input_ps constant v11.xyzw
dcl_input_ps linear v12.xyzw
dcl_input_ps linear v13.xyzw
dcl_input_ps linear v14.xyz
dcl_input_ps linear v15.xyzw
dcl_input_ps constant v16.yzw
dcl_input_ps linear v17.xyzw
dcl_input_ps linear v18.xyzw
dcl_input_ps linear v19.xyz
dcl_input_ps linear v20.xyz
dcl_input_ps constant v21.xzw
dcl_input_ps linear v22.xyzw
dcl_input_ps linear v23.xyzw
dcl_input_ps linear v24.xyz
dcl_input_ps linear v25.xyz
dcl_input_ps constant v26.xyw
dcl_input_ps linear v27.xyzw
dcl_input_ps constant v28.x
dcl_output o0.xyzw
dcl_temps 13
ult r0.xy, l(1, 1, 0, 0), cb1[9].ywyy
or r0.x, r0.y, r0.x
utof r1.xyzw, cb1[9].xyzw
div r0.yz, r1.xxyx, r1.zzwz
div r1.xy, l(1.000000, 1.000000, 1.000000, 1.000000), r1.zwzz
mad r0.yz, v4.xxyx, r1.xxyx, r0.yyzy
movc r0.xy, r0.xxxx, r0.yzyy, v4.xyxx
ieq r1.xy, cb1[8].xxxx, l(1, 2, 0, 0)
if_nz r1.x
  add r1.xzw, v5.xxyz, -v6.xxyz
  dp3 r0.w, r1.xzwx, r1.xzwx
  rsq r0.w, r0.w
  mul r1.xzw, r0.wwww, r1.xxzw
  dp3 r0.w, v1.xyzx, v1.xyzx
  rsq r0.w, r0.w
  mul r2.xyz, r0.wwww, v1.xyzx
  mul r3.xyz, r2.zxyz, v2.yzxy
  mad r3.xyz, r2.yzxy, v2.zxyz, -r3.xyzx
  dp3 r4.x, -r1.xzwx, v2.xyzx
  dp3 r4.y, -r1.xzwx, -r3.xyzx
  dp3 r0.w, -r1.xzwx, r2.xyzx
  mul r2.xy, r4.xyxx, l(-0.020000, -0.020000, 0.000000, 0.000000)
  div r2.xy, r2.xyxx, r0.wwww
  dp3 r0.w, -r1.xzwx, v1.xyzx
  mad r0.w, r0.w, l(-15.000000), l(20.000000)
  ftoi r1.x, r0.w
  round_z r0.w, r0.w
  div r0.w, l(1.000000, 1.000000, 1.000000, 1.000000), r0.w
  mul r1.zw, r0.wwww, r2.xxxy
  deriv_rtx_coarse r2.zw, r0.xxxy
  deriv_rty_coarse r4.xy, r0.xyxx
  add r3.w, -r0.w, l(1.000000)
  iadd r5.x, r1.x, l(1)
  mov r4.zw, l(0,0,0,0)
  mov r6.xyzw, l(0,0,0,0)
  mov r7.y, r3.w
  mov r7.xzw, l(0,0,1.000000,0)
  loop 
    ige r1.x, r7.x, r5.x
    breakc_nz r1.x
    add r8.xy, r0.xyxx, r4.zwzz
    sample_d_indexable(texture2d)(float,float,float,float) r1.x, r8.xyxx, t20.xyzw, s0, r2.zwzz, r4.xyxx
    add r1.x, r1.x, r7.w
    mul r8.w, r1.x, l(0.500000)
    lt r9.x, r7.y, r8.w
    add r9.y, -r7.z, r7.w
    mad r1.x, -r1.x, l(0.500000), r7.w
    add r1.x, r7.y, r1.x
    add r1.x, -r7.z, r1.x
    div r1.x, r9.y, r1.x
    mad r9.yz, r1.xxxx, r1.zzwz, r6.xxyx
    iadd r8.x, r7.x, l(1)
    mad r10.xy, r2.xyxx, r0.wwww, r4.zwzz
    add r8.y, -r0.w, r7.y
    movc r10.xy, r9.xxxx, r4.zwzz, r10.xyxx
    movc r6.xy, r9.xxxx, r6.xyxx, r4.zwzz
    movc r6.zw, r9.xxxx, r9.yyyz, r6.zzzw
    mov r5.yzw, r7.yyzw
    mov r8.z, r5.y
    movc r7.xyzw, r9.xxxx, r5.xyzw, r8.xyzw
    mov r4.zw, r10.xxxy
  endloop 
  add r1.xz, r0.xxyx, r6.zzwz
  sample_indexable(texture2d)(float,float,float,float) r0.w, r1.xzxx, t20.xzwy, s0
  mul r2.xyz, -r3.xyzx, r0.wwww
  mad r2.xyz, r0.wwww, v2.xyzx, r2.xyzx
  add r2.xyz, r2.xyzx, v1.xyzx
  dp3 r0.w, r2.xyzx, r2.xyzx
  rsq r0.w, r0.w
  mul r2.xyz, r0.wwww, r2.xyzx
else 
  mov r2.xyz, v1.xyzx
  mov r1.xz, r0.xxyx
endif 
if_nz r1.y
  add r3.xyz, v5.xyzx, -v6.xyzx
  dp3 r0.w, r3.xyzx, r3.xyzx
  rsq r0.w, r0.w
  mul r3.xyz, r0.wwww, r3.xyzx
  dp3 r0.w, r2.xyzx, r2.xyzx
  rsq r0.w, r0.w
  mul r4.xyz, r0.wwww, r2.xyzx
  mul r5.xyz, r4.zxyz, v2.yzxy
  mad r5.xyz, r4.yzxy, v2.zxyz, -r5.xyzx
  dp3 r6.x, -r3.xyzx, v2.xyzx
  dp3 r6.y, -r3.xyzx, -r5.xyzx
  dp3 r6.z, -r3.xyzx, r4.xyzx
  dp3 r0.w, r6.xyzx, r6.xyzx
  rsq r0.w, r0.w
  mul r3.xyz, r0.wwww, r6.xyzx
  div r3.xyz, r3.xyzx, r3.zzzz
  sample_indexable(texture2d)(float,float,float,float) r1.yw, r0.xyxx, t20.xwyz, s0
  mov_sat r1.y, r1.y
  mul r0.w, r1.y, r1.w
  add r1.y, r1.w, l(1.000000)
  div r0.w, r0.w, r1.y
  mul r0.w, r0.w, l(0.010000)
  mov r0.z, l(0)
  mad r4.xyz, r3.xyzx, r0.wwww, r0.xyzx
  sample_indexable(texture2d)(float,float,float,float) r1.yw, r4.xyxx, t20.xzyw, s0
  add_sat r0.w, -r4.z, r1.w
  mul r0.w, r0.w, r1.y
  add r1.y, r1.y, l(1.000000)
  div r0.w, r0.w, r1.y
  mul r0.w, r0.w, l(0.010000)
  mad r4.xyz, r3.xyzx, r0.wwww, r4.xyzx
  sample_indexable(texture2d)(float,float,float,float) r1.yw, r4.xyxx, t20.xzyw, s0
  add_sat r0.w, -r4.z, r1.w
  mul r0.w, r0.w, r1.y
  add r1.y, r1.y, l(1.000000)
  div r0.w, r0.w, r1.y
  mul r0.w, r0.w, l(0.010000)
  mad r4.xyz, r3.xyzx, r0.wwww, r4.xyzx
  sample_indexable(texture2d)(float,float,float,float) r1.yw, r4.xyxx, t20.xzyw, s0
  add_sat r0.w, -r4.z, r1.w
  mul r0.w, r0.w, r1.y
  add r1.y, r1.y, l(1.000000)
  div r0.w, r0.w, r1.y
  mul r0.w, r0.w, l(0.010000)
  mad r4.xyz, r3.xyzx, r0.wwww, r4.xyzx
  sample_indexable(texture2d)(float,float,float,float) r1.yw, r4.xyxx, t20.xzyw, s0
  add_sat r0.w, -r4.z, r1.w
  mul r0.w, r0.w, r1.y
  add r1.y, r1.y, l(1.000000)
  div r0.w, r0.w, r1.y
  mul r0.w, r0.w, l(0.010000)
  mad r4.xyz, r3.xyzx, r0.wwww, r4.xyzx
  sample_indexable(texture2d)(float,float,float,float) r1.yw, r4.xyxx, t20.xzyw, s0
  add_sat r0.w, -r4.z, r1.w
  mul r0.w, r0.w, r1.y
  add r1.y, r1.y, l(1.000000)
  div r0.w, r0.w, r1.y
  mul r0.w, r0.w, l(0.010000)
  mad r4.xyz, r3.xyzx, r0.wwww, r4.xyzx
  sample_indexable(texture2d)(float,float,float,float) r1.yw, r4.xyxx, t20.xzyw, s0
  add_sat r0.w, -r4.z, r1.w
  mul r0.w, r0.w, r1.y
  add r1.y, r1.y, l(1.000000)
  div r0.w, r0.w, r1.y
  mul r0.w, r0.w, l(0.010000)
  mad r4.xyz, r3.xyzx, r0.wwww, r4.xyzx
  sample_indexable(texture2d)(float,float,float,float) r1.yw, r4.xyxx, t20.xzyw, s0
  add_sat r0.w, -r4.z, r1.w
  mul r0.w, r0.w, r1.y
  add r1.y, r1.y, l(1.000000)
  div r0.w, r0.w, r1.y
  mul r0.w, r0.w, l(0.010000)
  mad r4.xyz, r3.xyzx, r0.wwww, r4.xyzx
  sample_indexable(texture2d)(float,float,float,float) r1.yw, r4.xyxx, t20.xzyw, s0
  add_sat r0.w, -r4.z, r1.w
  mul r0.w, r0.w, r1.y
  add r1.y, r1.y, l(1.000000)
  div r0.w, r0.w, r1.y
  mul r0.w, r0.w, l(0.010000)
  mad r4.xyz, r3.xyzx, r0.wwww, r4.xyzx
  sample_indexable(texture2d)(float,float,float,float) r1.yw, r4.xyxx, t20.xzyw, s0
  add_sat r0.w, -r4.z, r1.w
  mul r0.w, r0.w, r1.y
  add r1.y, r1.y, l(1.000000)
  div r0.w, r0.w, r1.y
  mul r0.w, r0.w, l(0.010000)
  mad r4.xyz, r3.xyzx, r0.wwww, r4.xyzx
  sample_indexable(texture2d)(float,float,float,float) r1.yw, r4.xyxx, t20.xzyw, s0
  add_sat r0.w, -r4.z, r1.w
  mul r0.w, r0.w, r1.y
  add r1.y, r1.y, l(1.000000)
  div r0.w, r0.w, r1.y
  mul r0.w, r0.w, l(0.010000)
  mad r4.xyz, r3.xyzx, r0.wwww, r4.xyzx
  sample_indexable(texture2d)(float,float,float,float) r1.yw, r4.xyxx, t20.xzyw, s0
  add_sat r0.w, -r4.z, r1.w
  mul r0.w, r0.w, r1.y
  add r1.y, r1.y, l(1.000000)
  div r0.w, r0.w, r1.y
  mul r0.w, r0.w, l(0.010000)
  mad r4.xyz, r3.xyzx, r0.wwww, r4.xyzx
  sample_indexable(texture2d)(float,float,float,float) r1.yw, r4.xyxx, t20.xzyw, s0
  add_sat r0.w, -r4.z, r1.w
  mul r0.w, r0.w, r1.y
  add r1.y, r1.y, l(1.000000)
  div r0.w, r0.w, r1.y
  mul r0.w, r0.w, l(0.010000)
  mad r4.xyz, r3.xyzx, r0.wwww, r4.xyzx
  sample_indexable(texture2d)(float,float,float,float) r1.yw, r4.xyxx, t20.xzyw, s0
  add_sat r0.w, -r4.z, r1.w
  mul r0.w, r0.w, r1.y
  add r1.y, r1.y, l(1.000000)
  div r0.w, r0.w, r1.y
  mul r0.w, r0.w, l(0.010000)
  mad r4.xyz, r3.xyzx, r0.wwww, r4.xyzx
  sample_indexable(texture2d)(float,float,float,float) r1.yw, r4.xyxx, t20.xzyw, s0
  add_sat r0.w, -r4.z, r1.w
  mul r0.w, r0.w, r1.y
  add r1.y, r1.y, l(1.000000)
  div r0.w, r0.w, r1.y
  mul r0.w, r3.z, r0.w
  mad r0.w, r0.w, l(0.010000), r4.z
  mul r3.xyz, r3.xyzx, r0.wwww
  mad r4.xyz, r3.xyzx, l(0.500000, 0.500000, 0.500000, 0.000000), r0.xyzx
  sample_indexable(texture2d)(float,float,float,float) r0.z, r4.xyxx, t20.xywz, s0
  lt r0.z, r4.z, r0.z
  if_nz r0.z
    mad r6.xyz, r3.xyzx, l(0.250000, 0.250000, 0.250000, 0.000000), r4.xyzx
  else 
    mad r6.xyz, -r3.xyzx, l(0.250000, 0.250000, 0.250000, 0.000000), r4.xyzx
  endif 
  sample_indexable(texture2d)(float,float,float,float) r0.z, r6.xyxx, t20.xywz, s0
  lt r0.z, r6.z, r0.z
  if_nz r0.z
    mad r4.xyz, r3.xyzx, l(0.125000, 0.125000, 0.125000, 0.000000), r6.xyzx
  else 
    mad r4.xyz, -r3.xyzx, l(0.125000, 0.125000, 0.125000, 0.000000), r6.xyzx
  endif 
  sample_indexable(texture2d)(float,float,float,float) r0.z, r4.xyxx, t20.xywz, s0
  lt r0.z, r4.z, r0.z
  if_nz r0.z
    mad r6.xyz, r3.xyzx, l(0.062500, 0.062500, 0.062500, 0.000000), r4.xyzx
  else 
    mad r6.xyz, -r3.xyzx, l(0.062500, 0.062500, 0.062500, 0.000000), r4.xyzx
  endif 
  sample_indexable(texture2d)(float,float,float,float) r0.z, r6.xyxx, t20.xywz, s0
  lt r0.z, r6.z, r0.z
  if_nz r0.z
    mad r4.xyz, r3.xyzx, l(0.031250, 0.031250, 0.031250, 0.000000), r6.xyzx
  else 
    mad r4.xyz, -r3.xyzx, l(0.031250, 0.031250, 0.031250, 0.000000), r6.xyzx
  endif 
  sample_indexable(texture2d)(float,float,float,float) r0.z, r4.xyxx, t20.xywz, s0
  lt r0.z, r4.z, r0.z
  if_nz r0.z
    mad r6.xyz, r3.xyzx, l(0.015625, 0.015625, 0.015625, 0.000000), r4.xyzx
  else 
    mad r6.xyz, -r3.xyzx, l(0.015625, 0.015625, 0.015625, 0.000000), r4.xyzx
  endif 
  sample_indexable(texture2d)(float,float,float,float) r0.z, r6.xyxx, t20.xywz, s0
  lt r0.z, r6.z, r0.z
  if_nz r0.z
    mad r1.xz, r3.xxyx, l(0.007813, 0.000000, 0.007813, 0.000000), r6.xxyx
  else 
    mad r1.xz, -r3.xxyx, l(0.007813, 0.000000, 0.007813, 0.000000), r6.xxyx
  endif 
  sample_indexable(texture2d)(float,float,float,float) r0.z, r1.xzxx, t20.xywz, s0
  mul r3.xyz, -r5.xyzx, r0.zzzz
  mad r3.xyz, r0.zzzz, v2.xyzx, r3.xyzx
  add r3.xyz, r2.xyzx, r3.xyzx
  dp3 r0.z, r3.xyzx, r3.xyzx
  rsq r0.z, r0.z
  mul r2.xyz, r0.zzzz, r3.xyzx
endif 
if_nz cb1[4].w
  sample_indexable(texture2d)(float,float,float,float) r0.zw, r1.xzxx, t18.zwxy, s0
  mad r0.zw, r0.zzzw, l(0.000000, 0.000000, 2.000000, 2.000000), l(0.000000, 0.000000, -1.000000, -1.000000)
  mul r0.zw, r0.zzzw, cb1[1].zzzz
  mul r3.xyz, r0.wwww, v3.xyzx
  mad r3.xyz, r0.zzzz, v2.xyzx, r3.xyzx
  add r3.xyz, r2.xyzx, r3.xyzx
  dp3 r0.z, r3.xyzx, r3.xyzx
  rsq r0.z, r0.z
  mul r2.xyz, r0.zzzz, r3.xyzx
endif 
resinfo_indexable(texture2d)(float,float,float,float) r0.zw, l(0), t11.zwxy
ult r3.xyzw, l(0, 1, 2, 3), v28.xxxx
if_nz v28.x
  ieq r1.y, v11.x, l(3)
  if_nz r1.y
    dp3 r1.y, v7.yzwy, v7.yzwy
    rsq r1.y, r1.y
    mul r4.xyz, r1.yyyy, v7.yzwy
    dp3 r1.y, v9.xyzx, v9.xyzx
    rsq r1.y, r1.y
    mul r5.xyz, r1.yyyy, v9.xyzx
    dp3 r1.y, r4.xyzx, r5.xyzx
    lt r1.w, r1.y, v4.z
    lt r2.w, v1.w, r1.y
    not r4.x, r2.w
    add r1.y, r1.y, -v1.w
    add r4.y, -v1.w, v4.z
    div r1.y, r1.y, r4.y
    movc r1.y, r2.w, r1.y, l(1.000000)
    movc r1.y, r1.w, r1.y, l(1.000000)
    and r1.w, r1.w, r4.x
    if_z r1.w
      if_nz v10.x
        div r4.xyz, v12.xyzx, v12.wwww
        lt r5.xyz, r4.xyzx, l(-1.000000, -1.000000, 0.000000, 0.000000)
        lt r6.xyz, l(1.000000, 1.000000, 3.000000, 0.000000), r4.xyzx
        or r2.w, r5.x, r6.x
        or r2.w, r5.y, r2.w
        or r2.w, r6.y, r2.w
        or r2.w, r5.z, r2.w
        or r2.w, r6.z, r2.w
        if_z r2.w
          add r5.xy, -r0.xyxx, r1.xzxx
          mad r4.xy, -r5.xyxx, l(0.200000, 0.200000, 0.000000, 0.000000), r4.xyxx
          mul r5.xy, r4.xyxx, l(0.500000, -0.500000, 0.000000, 0.000000)
          mad r6.xy, r4.xyxx, l(0.500000, -0.500000, 0.000000, 0.000000), l(0.500000, 0.500000, 0.000000, 0.000000)
          if_nz v10.y
            dp2 r4.w, r1.xzxx, l(23.140692, 2.665144, 0.000000, 0.000000)
            mad r4.w, r4.w, l(256.000000), l(0.000000)
            div r6.z, l(123456792.000000), r4.w
            ge r6.w, r6.z, -r6.z
            frc r6.z, |r6.z|
            movc r6.z, r6.w, r6.z, -r6.z
            mul r4.w, r4.w, r6.z
            sincos null, r4.w, r4.w
            frc r4.w, r4.w
            add r4.w, r4.w, l(0.500000)
            mul r6.zw, r0.zzzw, r4.wwww
            div r7.xy, l(-1.000000, -1.000000, 0.000000, 0.000000), r6.zwzz
            add r8.xy, r6.xyxx, r7.xyxx
            sample_c_lz_indexable(texture2d)(float,float,float,float) r4.w, r8.xyxx, t11.xxxx, s2, r4.z
            mul r4.w, r4.w, l(0.800000)
            mad r5.zw, r4.yyyx, l(0.000000, 0.000000, -0.500000, 0.500000), l(0.000000, 0.000000, 0.500000, 0.500000)
            mov r7.z, l(0.500000)
            add r8.xyzw, r5.xzwy, r7.zyxz
            sample_c_lz_indexable(texture2d)(float,float,float,float) r5.y, r8.xyxx, t11.xxxx, s2, r4.z
            mad r4.w, r5.y, l(1.600000), r4.w
            div r9.xy, l(1.000000, 1.000000, 1.000000, 1.000000), r6.zwzz
            mov r9.z, r7.y
            add r10.xyzw, r6.xyxy, r9.xzxy
            sample_c_lz_indexable(texture2d)(float,float,float,float) r5.y, r10.xyxx, t11.xxxx, s2, r4.z
            mad r4.w, r5.y, l(0.800000), r4.w
            sample_c_lz_indexable(texture2d)(float,float,float,float) r5.y, r8.zwzz, t11.xxxx, s2, r4.z
            mad r4.w, r5.y, l(0.800000), r4.w
            sample_c_lz_indexable(texture2d)(float,float,float,float) r5.w, r6.xyxx, t11.xxxx, s2, r4.z
            mad r4.w, r5.w, l(1.600000), r4.w
            mad r4.xy, r4.xyxx, l(0.500000, -0.500000, 0.000000, 0.000000), l(0.500000, 0.000000, 0.000000, 0.000000)
            mov r9.w, l(0.500000)
            add r4.xy, r4.xyxx, r9.xwxx
            sample_c_lz_indexable(texture2d)(float,float,float,float) r4.x, r4.xyxx, t11.xxxx, s2, r4.z
            mad r4.y, r4.x, l(0.800000), r4.w
            mad r4.y, r5.y, l(0.800000), r4.y
            mad r4.y, r5.w, l(1.600000), r4.y
            mad r4.x, r4.x, l(0.800000), r4.y
            mov r7.w, r9.y
            add r4.yw, r6.xxxy, r7.xxxw
            sample_c_lz_indexable(texture2d)(float,float,float,float) r4.y, r4.ywyy, t11.xxxx, s2, r4.z
            mad r4.x, r4.y, l(0.800000), r4.x
            add r4.yw, r5.xxxz, r7.zzzw
            sample_c_lz_indexable(texture2d)(float,float,float,float) r4.y, r4.ywyy, t11.xxxx, s2, r4.z
            mad r4.x, r4.y, l(1.600000), r4.x
            sample_c_lz_indexable(texture2d)(float,float,float,float) r4.y, r10.zwzz, t11.xxxx, s2, r4.z
            mad r4.x, r4.y, l(0.800000), r4.x
            if_nz v10.z
              mad r4.yw, |r4.zzzz|, l(0.000000, 0.100000, 0.000000, 0.100000), r6.xxxy
              add r5.xyzw, r7.xyxw, r4.ywyw
              sample_c_lz_indexable(texture2d)(float,float,float,float) r5.x, r5.xyxx, t11.xxxx, s2, r4.z
              mad r5.x, r5.x, l(0.200000), r4.x
              mov r8.xw, l(0,0,0,0)
              mov r8.y, r9.z
              add r6.zw, r4.yyyw, r8.xxxy
              sample_c_lz_indexable(texture2d)(float,float,float,float) r5.y, r6.zwzz, t11.xxxx, s2, r4.z
              mad r5.x, r5.y, l(0.400000), r5.x
              add r10.xyzw, r9.xzxy, r4.ywyw
              sample_c_lz_indexable(texture2d)(float,float,float,float) r5.y, r10.xyxx, t11.xxxx, s2, r4.z
              mad r5.x, r5.y, l(0.200000), r5.x
              mov r8.z, r7.x
              add r6.zw, r4.yyyw, r8.zzzw
              sample_c_lz_indexable(texture2d)(float,float,float,float) r5.y, r6.zwzz, t11.xxxx, s2, r4.z
              mad r5.x, r5.y, l(0.200000), r5.x
              sample_c_lz_indexable(texture2d)(float,float,float,float) r6.z, r4.ywyy, t11.xxxx, s2, r4.z
              mad r5.x, r6.z, l(0.400000), r5.x
              mov r7.x, r9.x
              mov r7.yz, l(0,0,0,0)
              add r7.xy, r4.ywyy, r7.xyxx
              sample_c_lz_indexable(texture2d)(float,float,float,float) r6.w, r7.xyxx, t11.xxxx, s2, r4.z
              mad r5.x, r6.w, l(0.200000), r5.x
              mad r5.x, r5.y, l(0.200000), r5.x
              mad r5.x, r6.z, l(0.400000), r5.x
              mad r5.x, r6.w, l(0.200000), r5.x
              sample_c_lz_indexable(texture2d)(float,float,float,float) r5.y, r5.zwzz, t11.xxxx, s2, r4.z
              mad r5.x, r5.y, l(0.200000), r5.x
              add r4.yw, r4.yyyw, r7.zzzw
              sample_c_lz_indexable(texture2d)(float,float,float,float) r4.y, r4.ywyy, t11.xxxx, s2, r4.z
              mad r4.y, r4.y, l(0.400000), r5.x
              sample_c_lz_indexable(texture2d)(float,float,float,float) r4.w, r10.zwzz, t11.xxxx, s2, r4.z
              mad r4.x, r4.w, l(0.200000), r4.y
            endif 
            mul r4.x, r4.x, l(0.062500)
          else 
            sample_c_lz_indexable(texture2d)(float,float,float,float) r4.y, r6.xyxx, t11.xxxx, s2, r4.z
            mul r4.x, r4.y, l(0.250000)
          endif 
        else 
          mov r4.x, l(1.000000)
        endif 
      else 
        sample_c_lz_indexable(texture2d)(float,float,float,float) r4.y, v12.xyxx, t11.xxxx, s2, v12.z
        mul r4.x, r4.y, l(0.250000)
        mov r2.w, l(0)
      endif 
    else 
      mov r4.x, l(1.000000)
      mov r2.w, l(-1)
    endif 
    or r1.w, r1.w, r2.w
  else 
    mov r4.x, l(1.000000)
    mov r1.yw, l(0,1.000000,0,0)
  endif 
  dp3 r2.w, r2.xyzx, r2.xyzx
  rsq r2.w, r2.w
  mul r4.yzw, r2.wwww, r2.xxyz
  dp3_sat r2.w, v7.yzwy, r4.yzwy
  mul r2.w, r2.w, v7.x
  mul r4.yzw, r2.wwww, v8.xxyz
  mul r4.yzw, r1.yyyy, r4.yyzw
  mul r4.xyz, r4.xxxx, r4.yzwy
  movc r4.xyz, r1.wwww, l(0,0,0,0), r4.xyzx
else 
  mov r4.xyz, l(0,0,0,0)
endif 
if_nz r3.y
  ieq r1.y, v16.y, l(3)
  if_nz r1.y
    dp3 r1.y, v13.yzwy, v13.yzwy
    rsq r1.y, r1.y
    mul r5.xyz, r1.yyyy, v13.yzwy
    dp3 r1.y, v15.xyzx, v15.xyzx
    rsq r1.y, r1.y
    mul r6.xyz, r1.yyyy, v15.xyzx
    dp3 r1.y, r5.xyzx, r6.xyzx
    lt r1.w, r1.y, v2.w
    lt r2.w, v3.w, r1.y
    not r4.w, r2.w
    add r1.y, r1.y, -v3.w
    add r5.x, v2.w, -v3.w
    div r1.y, r1.y, r5.x
    movc r1.y, r2.w, r1.y, l(1.000000)
    movc r1.y, r1.w, r1.y, l(1.000000)
    and r1.w, r1.w, r4.w
    if_z r1.w
      if_nz v11.y
        div r5.xyz, v17.xyzx, v17.wwww
        lt r6.xyz, r5.xyzx, l(-1.000000, -1.000000, 0.000000, 0.000000)
        lt r7.xyz, l(1.000000, 1.000000, 3.000000, 0.000000), r5.xyzx
        or r2.w, r6.x, r7.x
        or r2.w, r6.y, r2.w
        or r2.w, r7.y, r2.w
        or r2.w, r6.z, r2.w
        or r2.w, r7.z, r2.w
        if_z r2.w
          add r6.xy, -r0.xyxx, r1.xzxx
          mad r5.xy, -r6.xyxx, l(0.200000, 0.200000, 0.000000, 0.000000), r5.xyxx
          mul r6.xy, r5.xyxx, l(0.500000, -0.500000, 0.000000, 0.000000)
          mad r7.xy, r5.xyxx, l(0.500000, -0.500000, 0.000000, 0.000000), l(0.500000, 0.500000, 0.000000, 0.000000)
          if_nz v11.z
            dp2 r4.w, r1.xzxx, l(23.140692, 2.665144, 0.000000, 0.000000)
            mad r4.w, r4.w, l(256.000000), l(0.000000)
            div r5.w, l(123456792.000000), r4.w
            ge r7.z, r5.w, -r5.w
            frc r5.w, |r5.w|
            movc r5.w, r7.z, r5.w, -r5.w
            mul r4.w, r4.w, r5.w
            sincos null, r4.w, r4.w
            frc r4.w, r4.w
            add r4.w, r4.w, l(0.500000)
            mul r7.zw, r0.zzzw, r4.wwww
            div r8.xy, l(-1.000000, -1.000000, 0.000000, 0.000000), r7.zwzz
            add r9.xy, r7.xyxx, r8.xyxx
            sample_c_lz_indexable(texture2d)(float,float,float,float) r4.w, r9.xyxx, t11.xxxx, s2, r5.z
            mul r4.w, r4.w, l(0.800000)
            mad r6.zw, r5.yyyx, l(0.000000, 0.000000, -0.500000, 0.500000), l(0.000000, 0.000000, 0.500000, 0.500000)
            mov r8.z, l(0.500000)
            add r9.xyzw, r6.xzwy, r8.zyxz
            sample_c_lz_indexable(texture2d)(float,float,float,float) r5.w, r9.xyxx, t11.xxxx, s2, r5.z
            mad r4.w, r5.w, l(1.600000), r4.w
            div r10.xy, l(1.000000, 1.000000, 1.000000, 1.000000), r7.zwzz
            mov r10.z, r8.y
            add r11.xyzw, r7.xyxy, r10.xzxy
            sample_c_lz_indexable(texture2d)(float,float,float,float) r5.w, r11.xyxx, t11.xxxx, s2, r5.z
            mad r4.w, r5.w, l(0.800000), r4.w
            sample_c_lz_indexable(texture2d)(float,float,float,float) r5.w, r9.zwzz, t11.xxxx, s2, r5.z
            mad r4.w, r5.w, l(0.800000), r4.w
            sample_c_lz_indexable(texture2d)(float,float,float,float) r6.y, r7.xyxx, t11.xxxx, s2, r5.z
            mad r4.w, r6.y, l(1.600000), r4.w
            mad r5.xy, r5.xyxx, l(0.500000, -0.500000, 0.000000, 0.000000), l(0.500000, 0.000000, 0.000000, 0.000000)
            mov r10.w, l(0.500000)
            add r5.xy, r5.xyxx, r10.xwxx
            sample_c_lz_indexable(texture2d)(float,float,float,float) r5.x, r5.xyxx, t11.xxxx, s2, r5.z
            mad r4.w, r5.x, l(0.800000), r4.w
            mad r4.w, r5.w, l(0.800000), r4.w
            mad r4.w, r6.y, l(1.600000), r4.w
            mad r4.w, r5.x, l(0.800000), r4.w
            mov r8.w, r10.y
            add r5.xy, r7.xyxx, r8.xwxx
            sample_c_lz_indexable(texture2d)(float,float,float,float) r5.x, r5.xyxx, t11.xxxx, s2, r5.z
            mad r4.w, r5.x, l(0.800000), r4.w
            add r5.xy, r6.xzxx, r8.zwzz
            sample_c_lz_indexable(texture2d)(float,float,float,float) r5.x, r5.xyxx, t11.xxxx, s2, r5.z
            mad r4.w, r5.x, l(1.600000), r4.w
            sample_c_lz_indexable(texture2d)(float,float,float,float) r5.x, r11.zwzz, t11.xxxx, s2, r5.z
            mad r4.w, r5.x, l(0.800000), r4.w
            if_nz v11.w
              mad r5.xy, |r5.zzzz|, l(0.100000, 0.100000, 0.000000, 0.000000), r7.xyxx
              add r6.xyzw, r8.xyxw, r5.xyxy
              sample_c_lz_indexable(texture2d)(float,float,float,float) r5.w, r6.xyxx, t11.xxxx, s2, r5.z
              mad r5.w, r5.w, l(0.200000), r4.w
              mov r9.xw, l(0,0,0,0)
              mov r9.y, r10.z
              add r6.xy, r5.xyxx, r9.xyxx
              sample_c_lz_indexable(texture2d)(float,float,float,float) r6.x, r6.xyxx, t11.xxxx, s2, r5.z
              mad r5.w, r6.x, l(0.400000), r5.w
              add r11.xyzw, r10.xzxy, r5.xyxy
              sample_c_lz_indexable(texture2d)(float,float,float,float) r6.x, r11.xyxx, t11.xxxx, s2, r5.z
              mad r5.w, r6.x, l(0.200000), r5.w
              mov r9.z, r8.x
              add r6.xy, r5.xyxx, r9.zwzz
              sample_c_lz_indexable(texture2d)(float,float,float,float) r6.x, r6.xyxx, t11.xxxx, s2, r5.z
              mad r5.w, r6.x, l(0.200000), r5.w
              sample_c_lz_indexable(texture2d)(float,float,float,float) r6.y, r5.xyxx, t11.xxxx, s2, r5.z
              mad r5.w, r6.y, l(0.400000), r5.w
              mov r8.x, r10.x
              mov r8.yz, l(0,0,0,0)
              add r7.zw, r5.xxxy, r8.xxxy
              sample_c_lz_indexable(texture2d)(float,float,float,float) r7.z, r7.zwzz, t11.xxxx, s2, r5.z
              mad r5.w, r7.z, l(0.200000), r5.w
              mad r5.w, r6.x, l(0.200000), r5.w
              mad r5.w, r6.y, l(0.400000), r5.w
              mad r5.w, r7.z, l(0.200000), r5.w
              sample_c_lz_indexable(texture2d)(float,float,float,float) r6.x, r6.zwzz, t11.xxxx, s2, r5.z
              mad r5.w, r6.x, l(0.200000), r5.w
              add r5.xy, r5.xyxx, r8.zwzz
              sample_c_lz_indexable(texture2d)(float,float,float,float) r5.x, r5.xyxx, t11.xxxx, s2, r5.z
              mad r5.x, r5.x, l(0.400000), r5.w
              sample_c_lz_indexable(texture2d)(float,float,float,float) r5.y, r11.zwzz, t11.xxxx, s2, r5.z
              mad r4.w, r5.y, l(0.200000), r5.x
            endif 
            mul r4.w, r4.w, l(0.062500)
          else 
            sample_c_lz_indexable(texture2d)(float,float,float,float) r5.x, r7.xyxx, t11.xxxx, s2, r5.z
            mul r4.w, r5.x, l(0.250000)
          endif 
        else 
          mov r4.w, l(1.000000)
        endif 
      else 
        sample_c_lz_indexable(texture2d)(float,float,float,float) r5.x, v17.xyxx, t11.xxxx, s2, v17.z
        mul r4.w, r5.x, l(0.250000)
        mov r2.w, l(0)
      endif 
    else 
      mov r4.w, l(1.000000)
      mov r2.w, l(-1)
    endif 
    or r1.w, r1.w, r2.w
  else 
    mov r4.w, l(1.000000)
    mov r1.yw, l(0,1.000000,0,0)
  endif 
  dp3 r2.w, r2.xyzx, r2.xyzx
  rsq r2.w, r2.w
  mul r5.xyz, r2.wwww, r2.xyzx
  dp3_sat r2.w, v13.yzwy, r5.xyzx
  mul r2.w, r2.w, v13.x
  mul r5.xyz, r2.wwww, v14.xyzx
  mul r5.xyz, r1.yyyy, r5.xyzx
  mad r5.xyz, r5.xyzx, r4.wwww, r4.xyzx
  movc r4.xyz, r1.wwww, r4.xyzx, r5.xyzx
endif 
if_nz r3.z
  ieq r1.y, v21.z, l(3)
  if_nz r1.y
    dp3 r1.y, v18.yzwy, v18.yzwy
    rsq r1.y, r1.y
    mul r5.xyz, r1.yyyy, v18.yzwy
    dp3 r1.y, v20.xyzx, v20.xyzx
    rsq r1.y, r1.y
    mul r6.xyz, r1.yyyy, v20.xyzx
    dp3 r1.y, r5.xyzx, r6.xyzx
    lt r1.w, r1.y, v4.w
    lt r2.w, v5.w, r1.y
    not r4.w, r2.w
    add r1.y, r1.y, -v5.w
    add r5.x, v4.w, -v5.w
    div r1.y, r1.y, r5.x
    movc r1.y, r2.w, r1.y, l(1.000000)
    movc r1.y, r1.w, r1.y, l(1.000000)
    and r1.w, r1.w, r4.w
    if_z r1.w
      if_nz v16.z
        div r5.xyz, v22.xyzx, v22.wwww
        lt r6.xyz, r5.xyzx, l(-1.000000, -1.000000, 0.000000, 0.000000)
        lt r7.xyz, l(1.000000, 1.000000, 3.000000, 0.000000), r5.xyzx
        or r2.w, r6.x, r7.x
        or r2.w, r6.y, r2.w
        or r2.w, r7.y, r2.w
        or r2.w, r6.z, r2.w
        or r2.w, r7.z, r2.w
        if_z r2.w
          add r6.xy, -r0.xyxx, r1.xzxx
          mad r5.xy, -r6.xyxx, l(0.200000, 0.200000, 0.000000, 0.000000), r5.xyxx
          mul r6.xy, r5.xyxx, l(0.500000, -0.500000, 0.000000, 0.000000)
          mad r7.xy, r5.xyxx, l(0.500000, -0.500000, 0.000000, 0.000000), l(0.500000, 0.500000, 0.000000, 0.000000)
          if_nz v16.w
            dp2 r4.w, r1.xzxx, l(23.140692, 2.665144, 0.000000, 0.000000)
            mad r4.w, r4.w, l(256.000000), l(0.000000)
            div r5.w, l(123456792.000000), r4.w
            ge r7.z, r5.w, -r5.w
            frc r5.w, |r5.w|
            movc r5.w, r7.z, r5.w, -r5.w
            mul r4.w, r4.w, r5.w
            sincos null, r4.w, r4.w
            frc r4.w, r4.w
            add r4.w, r4.w, l(0.500000)
            mul r7.zw, r0.zzzw, r4.wwww
            div r8.xy, l(-1.000000, -1.000000, 0.000000, 0.000000), r7.zwzz
            add r9.xy, r7.xyxx, r8.xyxx
            sample_c_lz_indexable(texture2d)(float,float,float,float) r4.w, r9.xyxx, t11.xxxx, s2, r5.z
            mul r4.w, r4.w, l(0.800000)
            mad r6.zw, r5.yyyx, l(0.000000, 0.000000, -0.500000, 0.500000), l(0.000000, 0.000000, 0.500000, 0.500000)
            mov r8.z, l(0.500000)
            add r9.xyzw, r6.xzwy, r8.zyxz
            sample_c_lz_indexable(texture2d)(float,float,float,float) r5.w, r9.xyxx, t11.xxxx, s2, r5.z
            mad r4.w, r5.w, l(1.600000), r4.w
            div r10.xy, l(1.000000, 1.000000, 1.000000, 1.000000), r7.zwzz
            mov r10.z, r8.y
            add r11.xyzw, r7.xyxy, r10.xzxy
            sample_c_lz_indexable(texture2d)(float,float,float,float) r5.w, r11.xyxx, t11.xxxx, s2, r5.z
            mad r4.w, r5.w, l(0.800000), r4.w
            sample_c_lz_indexable(texture2d)(float,float,float,float) r5.w, r9.zwzz, t11.xxxx, s2, r5.z
            mad r4.w, r5.w, l(0.800000), r4.w
            sample_c_lz_indexable(texture2d)(float,float,float,float) r6.y, r7.xyxx, t11.xxxx, s2, r5.z
            mad r4.w, r6.y, l(1.600000), r4.w
            mad r5.xy, r5.xyxx, l(0.500000, -0.500000, 0.000000, 0.000000), l(0.500000, 0.000000, 0.000000, 0.000000)
            mov r10.w, l(0.500000)
            add r5.xy, r5.xyxx, r10.xwxx
            sample_c_lz_indexable(texture2d)(float,float,float,float) r5.x, r5.xyxx, t11.xxxx, s2, r5.z
            mad r4.w, r5.x, l(0.800000), r4.w
            mad r4.w, r5.w, l(0.800000), r4.w
            mad r4.w, r6.y, l(1.600000), r4.w
            mad r4.w, r5.x, l(0.800000), r4.w
            mov r8.w, r10.y
            add r5.xy, r7.xyxx, r8.xwxx
            sample_c_lz_indexable(texture2d)(float,float,float,float) r5.x, r5.xyxx, t11.xxxx, s2, r5.z
            mad r4.w, r5.x, l(0.800000), r4.w
            add r5.xy, r6.xzxx, r8.zwzz
            sample_c_lz_indexable(texture2d)(float,float,float,float) r5.x, r5.xyxx, t11.xxxx, s2, r5.z
            mad r4.w, r5.x, l(1.600000), r4.w
            sample_c_lz_indexable(texture2d)(float,float,float,float) r5.x, r11.zwzz, t11.xxxx, s2, r5.z
            mad r4.w, r5.x, l(0.800000), r4.w
            if_nz v21.x
              mad r5.xy, |r5.zzzz|, l(0.100000, 0.100000, 0.000000, 0.000000), r7.xyxx
              add r6.xyzw, r8.xyxw, r5.xyxy
              sample_c_lz_indexable(texture2d)(float,float,float,float) r5.w, r6.xyxx, t11.xxxx, s2, r5.z
              mad r5.w, r5.w, l(0.200000), r4.w
              mov r9.xw, l(0,0,0,0)
              mov r9.y, r10.z
              add r6.xy, r5.xyxx, r9.xyxx
              sample_c_lz_indexable(texture2d)(float,float,float,float) r6.x, r6.xyxx, t11.xxxx, s2, r5.z
              mad r5.w, r6.x, l(0.400000), r5.w
              add r11.xyzw, r10.xzxy, r5.xyxy
              sample_c_lz_indexable(texture2d)(float,float,float,float) r6.x, r11.xyxx, t11.xxxx, s2, r5.z
              mad r5.w, r6.x, l(0.200000), r5.w
              mov r9.z, r8.x
              add r6.xy, r5.xyxx, r9.zwzz
              sample_c_lz_indexable(texture2d)(float,float,float,float) r6.x, r6.xyxx, t11.xxxx, s2, r5.z
              mad r5.w, r6.x, l(0.200000), r5.w
              sample_c_lz_indexable(texture2d)(float,float,float,float) r6.y, r5.xyxx, t11.xxxx, s2, r5.z
              mad r5.w, r6.y, l(0.400000), r5.w
              mov r8.x, r10.x
              mov r8.yz, l(0,0,0,0)
              add r7.zw, r5.xxxy, r8.xxxy
              sample_c_lz_indexable(texture2d)(float,float,float,float) r7.z, r7.zwzz, t11.xxxx, s2, r5.z
              mad r5.w, r7.z, l(0.200000), r5.w
              mad r5.w, r6.x, l(0.200000), r5.w
              mad r5.w, r6.y, l(0.400000), r5.w
              mad r5.w, r7.z, l(0.200000), r5.w
              sample_c_lz_indexable(texture2d)(float,float,float,float) r6.x, r6.zwzz, t11.xxxx, s2, r5.z
              mad r5.w, r6.x, l(0.200000), r5.w
              add r5.xy, r5.xyxx, r8.zwzz
              sample_c_lz_indexable(texture2d)(float,float,float,float) r5.x, r5.xyxx, t11.xxxx, s2, r5.z
              mad r5.x, r5.x, l(0.400000), r5.w
              sample_c_lz_indexable(texture2d)(float,float,float,float) r5.y, r11.zwzz, t11.xxxx, s2, r5.z
              mad r4.w, r5.y, l(0.200000), r5.x
            endif 
            mul r4.w, r4.w, l(0.062500)
          else 
            sample_c_lz_indexable(texture2d)(float,float,float,float) r5.x, r7.xyxx, t11.xxxx, s2, r5.z
            mul r4.w, r5.x, l(0.250000)
          endif 
        else 
          mov r4.w, l(1.000000)
        endif 
      else 
        sample_c_lz_indexable(texture2d)(float,float,float,float) r5.x, v22.xyxx, t11.xxxx, s2, v22.z
        mul r4.w, r5.x, l(0.250000)
        mov r2.w, l(0)
      endif 
    else 
      mov r4.w, l(1.000000)
      mov r2.w, l(-1)
    endif 
    or r1.w, r1.w, r2.w
  else 
    mov r4.w, l(1.000000)
    mov r1.yw, l(0,1.000000,0,0)
  endif 
  dp3 r2.w, r2.xyzx, r2.xyzx
  rsq r2.w, r2.w
  mul r5.xyz, r2.wwww, r2.xyzx
  dp3_sat r2.w, v18.yzwy, r5.xyzx
  mul r2.w, r2.w, v18.x
  mul r5.xyz, r2.wwww, v19.xyzx
  mul r5.xyz, r1.yyyy, r5.xyzx
  mad r5.xyz, r5.xyzx, r4.wwww, r4.xyzx
  movc r4.xyz, r1.wwww, r4.xyzx, r5.xyzx
endif 
if_nz r3.w
  ieq r1.y, v26.w, l(3)
  if_nz r1.y
    dp3 r1.y, v23.yzwy, v23.yzwy
    rsq r1.y, r1.y
    mul r5.xyz, r1.yyyy, v23.yzwy
    dp3 r1.y, v25.xyzx, v25.xyzx
    rsq r1.y, r1.y
    mul r6.xyz, r1.yyyy, v25.xyzx
    dp3 r1.y, r5.xyzx, r6.xyzx
    lt r1.w, r1.y, v9.w
    lt r2.w, v15.w, r1.y
    not r4.w, r2.w
    add r1.y, r1.y, -v15.w
    add r5.x, v9.w, -v15.w
    div r1.y, r1.y, r5.x
    movc r1.y, r2.w, r1.y, l(1.000000)
    movc r1.y, r1.w, r1.y, l(1.000000)
    and r1.w, r1.w, r4.w
    if_z r1.w
      if_nz v21.w
        div r5.xyz, v27.xyzx, v27.wwww
        lt r6.xyz, r5.xyzx, l(-1.000000, -1.000000, 0.000000, 0.000000)
        lt r7.xyz, l(1.000000, 1.000000, 3.000000, 0.000000), r5.xyzx
        or r2.w, r6.x, r7.x
        or r2.w, r6.y, r2.w
        or r2.w, r7.y, r2.w
        or r2.w, r6.z, r2.w
        or r2.w, r7.z, r2.w
        if_z r2.w
          add r0.xy, -r0.xyxx, r1.xzxx
          mad r0.xy, -r0.xyxx, l(0.200000, 0.200000, 0.000000, 0.000000), r5.xyxx
          mul r6.xy, r0.xyxx, l(0.500000, -0.500000, 0.000000, 0.000000)
          mad r5.xy, r0.xyxx, l(0.500000, -0.500000, 0.000000, 0.000000), l(0.500000, 0.500000, 0.000000, 0.000000)
          if_nz v26.x
            dp2 r4.w, r1.xzxx, l(23.140692, 2.665144, 0.000000, 0.000000)
            mad r4.w, r4.w, l(256.000000), l(0.000000)
            div r5.w, l(123456792.000000), r4.w
            ge r7.x, r5.w, -r5.w
            frc r5.w, |r5.w|
            movc r5.w, r7.x, r5.w, -r5.w
            mul r4.w, r4.w, r5.w
            sincos null, r4.w, r4.w
            frc r4.w, r4.w
            add r4.w, r4.w, l(0.500000)
            mul r0.zw, r0.zzzw, r4.wwww
            div r7.xy, l(-1.000000, -1.000000, 0.000000, 0.000000), r0.zwzz
            add r8.xy, r5.xyxx, r7.xyxx
            sample_c_lz_indexable(texture2d)(float,float,float,float) r4.w, r8.xyxx, t11.xxxx, s2, r5.z
            mul r4.w, r4.w, l(0.800000)
            mad r6.zw, r0.yyyx, l(0.000000, 0.000000, -0.500000, 0.500000), l(0.000000, 0.000000, 0.500000, 0.500000)
            mov r7.z, l(0.500000)
            add r8.xyzw, r6.xzwy, r7.zyxz
            sample_c_lz_indexable(texture2d)(float,float,float,float) r5.w, r8.xyxx, t11.xxxx, s2, r5.z
            mad r4.w, r5.w, l(1.600000), r4.w
            div r9.xy, l(1.000000, 1.000000, 1.000000, 1.000000), r0.zwzz
            mov r9.z, r7.y
            add r10.xyzw, r5.xyxy, r9.xzxy
            sample_c_lz_indexable(texture2d)(float,float,float,float) r0.z, r10.xyxx, t11.xxxx, s2, r5.z
            mad r0.z, r0.z, l(0.800000), r4.w
            sample_c_lz_indexable(texture2d)(float,float,float,float) r0.w, r8.zwzz, t11.xxxx, s2, r5.z
            mad r0.z, r0.w, l(0.800000), r0.z
            sample_c_lz_indexable(texture2d)(float,float,float,float) r4.w, r5.xyxx, t11.xxxx, s2, r5.z
            mad r0.z, r4.w, l(1.600000), r0.z
            mad r0.xy, r0.xyxx, l(0.500000, -0.500000, 0.000000, 0.000000), l(0.500000, 0.000000, 0.000000, 0.000000)
            mov r9.w, l(0.500000)
            add r0.xy, r0.xyxx, r9.xwxx
            sample_c_lz_indexable(texture2d)(float,float,float,float) r0.x, r0.xyxx, t11.xxxx, s2, r5.z
            mad r0.y, r0.x, l(0.800000), r0.z
            mad r0.y, r0.w, l(0.800000), r0.y
            mad r0.y, r4.w, l(1.600000), r0.y
            mad r0.x, r0.x, l(0.800000), r0.y
            mov r7.w, r9.y
            add r0.yz, r5.xxyx, r7.xxwx
            sample_c_lz_indexable(texture2d)(float,float,float,float) r0.y, r0.yzyy, t11.xxxx, s2, r5.z
            mad r0.x, r0.y, l(0.800000), r0.x
            add r0.yz, r6.xxzx, r7.zzwz
            sample_c_lz_indexable(texture2d)(float,float,float,float) r0.y, r0.yzyy, t11.xxxx, s2, r5.z
            mad r0.x, r0.y, l(1.600000), r0.x
            sample_c_lz_indexable(texture2d)(float,float,float,float) r0.y, r10.zwzz, t11.xxxx, s2, r5.z
            mad r0.x, r0.y, l(0.800000), r0.x
            if_nz v26.y
              mad r0.yz, |r5.zzzz|, l(0.000000, 0.100000, 0.100000, 0.000000), r5.xxyx
              add r6.xyzw, r7.xyxw, r0.yzyz
              sample_c_lz_indexable(texture2d)(float,float,float,float) r0.w, r6.xyxx, t11.xxxx, s2, r5.z
              mad r0.w, r0.w, l(0.200000), r0.x
              mov r8.xw, l(0,0,0,0)
              mov r8.y, r9.z
              add r6.xy, r0.yzyy, r8.xyxx
              sample_c_lz_indexable(texture2d)(float,float,float,float) r4.w, r6.xyxx, t11.xxxx, s2, r5.z
              mad r0.w, r4.w, l(0.400000), r0.w
              add r10.xyzw, r9.xzxy, r0.yzyz
              sample_c_lz_indexable(texture2d)(float,float,float,float) r4.w, r10.xyxx, t11.xxxx, s2, r5.z
              mad r0.w, r4.w, l(0.200000), r0.w
              mov r8.z, r7.x
              add r6.xy, r0.yzyy, r8.zwzz
              sample_c_lz_indexable(texture2d)(float,float,float,float) r4.w, r6.xyxx, t11.xxxx, s2, r5.z
              mad r0.w, r4.w, l(0.200000), r0.w
              sample_c_lz_indexable(texture2d)(float,float,float,float) r5.w, r0.yzyy, t11.xxxx, s2, r5.z
              mad r0.w, r5.w, l(0.400000), r0.w
              mov r7.x, r9.x
              mov r7.yz, l(0,0,0,0)
              add r6.xy, r0.yzyy, r7.xyxx
              sample_c_lz_indexable(texture2d)(float,float,float,float) r6.x, r6.xyxx, t11.xxxx, s2, r5.z
              mad r0.w, r6.x, l(0.200000), r0.w
              mad r0.w, r4.w, l(0.200000), r0.w
              mad r0.w, r5.w, l(0.400000), r0.w
              mad r0.w, r6.x, l(0.200000), r0.w
              sample_c_lz_indexable(texture2d)(float,float,float,float) r4.w, r6.zwzz, t11.xxxx, s2, r5.z
              mad r0.w, r4.w, l(0.200000), r0.w
              add r0.yz, r0.yyzy, r7.zzwz
              sample_c_lz_indexable(texture2d)(float,float,float,float) r0.y, r0.yzyy, t11.xxxx, s2, r5.z
              mad r0.y, r0.y, l(0.400000), r0.w
              sample_c_lz_indexable(texture2d)(float,float,float,float) r0.z, r10.zwzz, t11.xxxx, s2, r5.z
              mad r0.x, r0.z, l(0.200000), r0.y
            endif 
            mul r0.x, r0.x, l(0.062500)
          else 
            sample_c_lz_indexable(texture2d)(float,float,float,float) r0.y, r5.xyxx, t11.xxxx, s2, r5.z
            mul r0.x, r0.y, l(0.250000)
          endif 
        else 
          mov r0.x, l(1.000000)
        endif 
      else 
        sample_c_lz_indexable(texture2d)(float,float,float,float) r0.y, v27.xyxx, t11.xxxx, s2, v27.z
        mul r0.x, r0.y, l(0.250000)
        mov r2.w, l(0)
      endif 
    else 
      mov r0.x, l(1.000000)
      mov r2.w, l(-1)
    endif 
    or r0.y, r1.w, r2.w
  else 
    mov r1.y, l(1.000000)
    mov r0.xy, l(1.000000,0,0,0)
  endif 
  dp3 r0.z, r2.xyzx, r2.xyzx
  rsq r0.z, r0.z
  mul r5.xyz, r0.zzzz, r2.xyzx
  dp3_sat r0.z, v23.yzwy, r5.xyzx
  mul r0.z, r0.z, v23.x
  mul r5.xyz, r0.zzzz, v24.xyzx
  mul r5.xyz, r1.yyyy, r5.xyzx
  mad r0.xzw, r5.xxyz, r0.xxxx, r4.xxyz
  movc r4.xyz, r0.yyyy, r4.xyzx, r0.xzwx
endif 
mul_sat r0.xyz, r4.xyzx, cb1[1].yyyy
if_nz cb1[4].z
  dp3 r0.w, v7.yzwy, v7.yzwy
  rsq r0.w, r0.w
  add r4.xyz, v5.xyzx, -v6.xyzx
  dp3 r1.y, r4.xyzx, r4.xyzx
  rsq r1.y, r1.y
  mul r4.xyz, r1.yyyy, r4.xyzx
  mad r5.xyz, v7.yzwy, r0.wwww, r4.xyzx
  dp3 r0.w, r5.xyzx, r5.xyzx
  rsq r0.w, r0.w
  mul r5.xyz, r0.wwww, r5.xyzx
  dp3 r0.w, r2.xyzx, r2.xyzx
  rsq r0.w, r0.w
  mul r6.xyz, r0.wwww, r2.xyzx
  dp3_sat r0.w, r6.xyzx, r5.xyzx
  log r0.w, r0.w
  mul r0.w, r0.w, cb1[1].x
  exp r0.w, r0.w
  and r0.w, r0.w, r3.x
  dp3 r1.y, v13.yzwy, v13.yzwy
  rsq r1.y, r1.y
  mad r5.xyz, v13.yzwy, r1.yyyy, r4.xyzx
  dp3 r1.y, r5.xyzx, r5.xyzx
  rsq r1.y, r1.y
  mul r5.xyz, r1.yyyy, r5.xyzx
  dp3_sat r1.y, r6.xyzx, r5.xyzx
  log r1.y, r1.y
  mul r1.y, r1.y, cb1[1].x
  exp r1.y, r1.y
  add r1.y, r0.w, r1.y
  movc r0.w, r3.y, r1.y, r0.w
  dp3 r1.y, v18.yzwy, v18.yzwy
  rsq r1.y, r1.y
  mad r5.xyz, v18.yzwy, r1.yyyy, r4.xyzx
  dp3 r1.y, r5.xyzx, r5.xyzx
  rsq r1.y, r1.y
  mul r5.xyz, r1.yyyy, r5.xyzx
  dp3_sat r1.y, r6.xyzx, r5.xyzx
  log r1.y, r1.y
  mul r1.y, r1.y, cb1[1].x
  exp r1.y, r1.y
  add r1.y, r0.w, r1.y
  movc r0.w, r3.z, r1.y, r0.w
  dp3 r1.y, v23.yzwy, v23.yzwy
  rsq r1.y, r1.y
  mad r4.xyz, v23.yzwy, r1.yyyy, r4.xyzx
  dp3 r1.y, r4.xyzx, r4.xyzx
  rsq r1.y, r1.y
  mul r4.xyz, r1.yyyy, r4.xyzx
  dp3_sat r1.y, r6.xyzx, r4.xyzx
  log r1.y, r1.y
  mul r1.y, r1.y, cb1[1].x
  exp r1.y, r1.y
  add r1.y, r0.w, r1.y
  movc r0.w, r3.w, r1.y, r0.w
  if_nz cb1[6].z
    mul r4.xyz, r0.xyzx, r0.wwww
    add r4.xyz, r4.xyzx, r4.xyzx
  else 
    if_nz cb1[5].z
      sample_indexable(texture2d)(float,float,float,float) r5.xyz, r1.xzxx, t15.xyzw, s0
      add r5.xyz, r5.xyzx, r5.xyzx
      mul r6.xyz, r0.xyzx, r0.wwww
      mul r4.xyz, r5.xyzx, r6.xyzx
    else 
      sample_indexable(texture2d)(float,float,float,float) r5.xyz, r1.xzxx, t17.xyzw, s0
      add r5.xyz, r5.xyzx, r5.xyzx
      mul r6.xyz, r0.xyzx, r0.wwww
      mul r4.xyz, r5.xyzx, r6.xyzx
    endif 
  endif 
else 
  mov r4.xyz, l(0,0,0,0)
endif 
if_nz cb1[4].x
  sample_indexable(texture2d)(float,float,float,float) r5.xyzw, r1.xzxx, t15.xyzw, s0
else 
  movc r5.w, cb1[5].x, l(0), l(1.000000)
  mov r5.xyz, r5.wwww
endif 
if_nz cb1[7].z
  resinfo_indexable(texture2d)(float,float,float,float)_uint r1.yw, l(0), t15.zxwy
  utof r6.xyzw, r1.ywyw
  ld_indexable(texture2d)(float,float,float,float) r7.xyz, l(0, 0, 0, 0), t15.xyzw
  mad r6.xyzw, r1.xzxz, r6.xyzw, l(-0.500000, -0.500000, 0.500000, 0.500000)
  ftoi r8.xyzw, r6.zyxy
  mov r9.xy, r8.zwzz
  mov r9.zw, l(0,0,0,0)
  ld_indexable(texture2d)(float,float,float,float) r9.xyzw, r9.xyzw, t15.xyzw
  mov r8.zw, l(0,0,0,0)
  ld_indexable(texture2d)(float,float,float,float) r8.xyzw, r8.xyzw, t15.xyzw
  ftoi r10.xyzw, r6.zwxw
  mov r11.xy, r10.zwzz
  mov r11.zw, l(0,0,0,0)
  ld_indexable(texture2d)(float,float,float,float) r11.xyzw, r11.xyzw, t15.xyzw
  mov r10.zw, l(0,0,0,0)
  ld_indexable(texture2d)(float,float,float,float) r10.xyzw, r10.xyzw, t15.xyzw
  eq r12.xyz, r9.xyzx, r7.xyzx
  and r0.w, r12.y, r12.x
  and r0.w, r12.z, r0.w
  movc r9.xyzw, r0.wwww, l(0,0,0,0), r9.wxyz
  eq r12.xyz, r8.xyzx, r7.xyzx
  and r0.w, r12.y, r12.x
  and r0.w, r12.z, r0.w
  movc r8.xyzw, r0.wwww, l(0,0,0,0), r8.wxyz
  eq r12.xyz, r11.xyzx, r7.xyzx
  and r0.w, r12.y, r12.x
  and r0.w, r12.z, r0.w
  movc r11.xyzw, r0.wwww, l(0,0,0,0), r11.wxyz
  eq r7.xyz, r10.xyzx, r7.xyzx
  and r0.w, r7.y, r7.x
  and r0.w, r7.z, r0.w
  movc r7.xyzw, r0.wwww, l(0,0,0,0), r10.wxyz
  frc r1.yw, r6.xxxy
  add r6.xyzw, -r9.xyzw, r8.xyzw
  mad r6.xyzw, r6.xyzw, r1.yyyy, r9.xyzw
  add r7.xyzw, -r11.xyzw, r7.xyzw
  mad r7.xyzw, r7.xyzw, r1.yyyy, r11.xyzw
  add r7.xyzw, -r6.xyzw, r7.xyzw
  mad r5.xyzw, r7.yzwx, r1.wwww, r6.yzwx
endif 
if_nz cb1[4].y
  if_nz cb1[7].y
    mov r6.xyz, cb1[0].xyzx
  else 
    if_nz cb1[5].y
      sample_indexable(texture2d)(float,float,float,float) r7.xyz, r1.xzxx, t15.xyzw, s0
      add r8.xyz, -r0.xyzx, l(1.000000, 1.000000, 1.000000, 0.000000)
      mul r6.xyz, r7.xyzx, r8.xyzx
    else 
      sample_indexable(texture2d)(float,float,float,float) r7.xyz, r1.xzxx, t16.xyzw, s0
      add r8.xyz, -r0.xyzx, l(1.000000, 1.000000, 1.000000, 0.000000)
      mul r6.xyz, r7.xyzx, r8.xyzx
    endif 
  endif 
else 
  mov r6.xyz, l(0,0,0,0)
endif 
mul r7.xyz, r0.xyzx, r5.xyzx
movc r5.xyz, cb1[7].xxxx, r7.xyzx, r5.xyzx
add r5.xyz, r5.xyzx, cb1[0].xyzx
add r5.xyz, r6.xyzx, r5.xyzx
add r6.xyz, r4.xyzx, r5.xyzx
if_nz cb1[7].w
  add r5.xyz, v5.xyzx, -v6.xyzx
  dp3 r0.w, r5.xyzx, r5.xyzx
  rsq r0.w, r0.w
  mul r5.xyz, r0.wwww, r5.xyzx
  dp3 r0.w, r5.xyzx, r2.xyzx
  add r1.y, r0.w, r0.w
  mad r1.yw, r2.xxxy, -r1.yyyy, r5.xxxy
  mad r2.w, -r0.w, r0.w, l(1.000000)
  mad r2.w, -r2.w, l(0.980100), l(1.000000)
  sqrt r3.x, r2.w
  mad r0.w, r0.w, l(0.990000), r3.x
  ge r2.w, r2.w, l(0.000000)
  mul r7.xy, r2.xyxx, r0.wwww
  mad r5.xy, r5.xyxx, l(0.990000, 0.990000, 0.000000, 0.000000), -r7.xyxx
  and r5.xy, r2.wwww, r5.xyxx
  sample_indexable(texture2d)(float,float,float,float) r5.xyz, r5.xyxx, t19.xyzw, s0
  sample_indexable(texture2d)(float,float,float,float) r7.xyz, r1.ywyy, t19.xyzw, s0
  if_nz cb1[8].w
    sample_indexable(texture2d)(float,float,float,float) r0.w, r1.xzxx, t19.xyzw, s0
    add r8.xyz, -r5.xyzx, r7.xyzx
    mad r8.xyz, r8.xyzx, l(0.500000, 0.500000, 0.500000, 0.000000), r5.xyzx
    div r8.xyz, r8.xyzx, cb1[2].wwww
    mul r8.xyz, r0.wwww, r8.xyzx
    dp3 r0.w, r6.xyzx, r6.xyzx
    mad r6.xyz, r8.xyzx, r0.wwww, r6.xyzx
  else 
    add r7.xyz, -r5.xyzx, r7.xyzx
    mad r5.xyz, r7.xyzx, l(0.500000, 0.500000, 0.500000, 0.000000), r5.xyzx
    div r5.xyz, r5.xyzx, cb1[2].wwww
    dp3 r0.w, r6.xyzx, r6.xyzx
    mad r6.xyz, r5.xyzx, r0.wwww, r6.xyzx
  endif 
endif 
mov_sat r5.w, r5.w
add r0.w, l(1.000000), -cb1[1].w
mad r0.w, r5.w, r0.w, cb1[0].w
movc r6.w, cb1[4].x, r0.w, cb1[0].w
ine r1.yw, cb1[8].yyyx, l(0, 0, 0, 0)
ine r0.w, cb1[4].w, l(0)
and r0.w, r0.w, r1.y
and r0.w, r1.w, r0.w
if_nz r0.w
  add r5.xyz, v5.xyzx, -v6.xyzx
  dp3 r0.w, r5.xyzx, r5.xyzx
  rsq r0.w, r0.w
  mul r7.xyz, r0.wwww, r5.xyzx
  dp3 r1.y, v7.yzwy, v7.yzwy
  rsq r1.y, r1.y
  mul r8.xyz, r1.yyyy, v7.yzwy
  mad r5.xyz, r5.xyzx, r0.wwww, r8.xyzx
  dp3 r0.w, r5.xyzx, r5.xyzx
  rsq r0.w, r0.w
  mul r5.xyz, r0.wwww, r5.xyzx
  dp3 r0.w, r5.xyzx, r8.xyzx
  mad r9.x, r0.w, l(0.500000), l(0.500000)
  dp3 r0.w, r2.xyzx, r5.xyzx
  mad r0.w, r0.w, l(0.500000), l(0.500000)
  add r9.y, -r0.w, l(1.000000)
  dp3 r0.w, r8.xyzx, r2.xyzx
  mad r5.x, r0.w, l(0.500000), l(0.500000)
  dp3 r0.w, r2.xyzx, r7.xyzx
  mad r0.w, r0.w, l(0.500000), l(0.500000)
  add r5.y, -r0.w, l(1.000000)
  sample_indexable(texture2d)(float,float,float,float) r7.xyz, r9.xyxx, t20.xyzw, s0
  sample_indexable(texture2d)(float,float,float,float) r5.xyz, r5.xyxx, t18.xyzw, s0
  mul r5.xyz, r5.xyzx, v8.xyzx
  mad r5.xyz, r5.xyzx, cb1[0].xyzx, r7.xyzx
  add r0.xyz, r0.xyzx, r5.xyzx
  utof r0.w, v28.x
  div r1.y, l(20.000000), cb1[3].y
  mul r0.w, r0.w, r1.y
  div r0.xyz, r0.xyzx, r0.wwww
  dp3 r0.w, r6.xyzx, r6.xyzx
  mad r6.xyz, r0.xyzx, r0.wwww, r6.xyzx
endif 
if_nz cb1[8].z
  sample_indexable(texture2d)(float,float,float,float) r0.xyz, r1.xzxx, t15.xyzw, s0
  sample_indexable(texture2d)(float,float,float,float) r1.xyz, r1.xzxx, t21.xyzw, s0
  dp3 r0.w, r1.xyzx, r1.xyzx
  sqrt r0.w, r0.w
  if_nz v28.x
    dp3 r1.x, v7.yzwy, v7.yzwy
    rsq r1.x, r1.x
    mul r1.yzw, r1.xxxx, v7.yyzw
    add r5.xyzw, -v6.xyzw, v12.xyzw
    dp4 r2.w, r5.xyzw, r5.xyzw
    sqrt r2.w, r2.w
    div r2.w, l(1.000000, 1.000000, 1.000000, 1.000000), r2.w
    lt r3.x, r2.w, l(0.100000)
    if_nz r3.x
      mov r3.x, l(1.000000)
    else 
      mul r3.x, r2.w, l(10.000000)
    endif 
    add r5.xyz, v5.xyzx, -v6.xyzx
    dp3 r2.w, r5.xyzx, r5.xyzx
    rsq r2.w, r2.w
    mul r5.xyz, r2.wwww, r5.xyzx
    dp3 r2.w, r1.yzwy, r2.xyzx
    mad r4.w, r2.w, l(0.500000), l(0.500000)
    mul r4.w, r3.x, r4.w
    dp3 r5.w, -r2.xyzx, r1.yzwy
    max r5.w, r5.w, l(0.000000)
    dp3 r1.y, -r5.xyzx, r1.yzwy
    mad r1.y, r1.y, l(0.500000), l(0.500000)
    mul r1.y, r1.y, cb1[3].x
    mad r1.y, cb1[3].x, r5.w, r1.y
    mul r1.y, r3.x, r1.y
    mul r1.yzw, r1.yyyy, cb1[2].xxyz
    mul r1.yzw, r0.wwww, r1.yyzw
    dp3 r5.x, r2.xyzx, r5.xyzx
    max r5.x, r5.x, l(0.000000)
    add r5.y, -r5.x, l(1.000000)
    mul r5.y, r5.y, r5.y
    max r2.w, r2.w, l(0.000000)
    mul r7.xyz, r4.xyzx, r2.wwww
    mul r5.yzw, r5.yyyy, r7.xxyz
    mad r7.xyz, r4.wwww, r0.xyzx, r1.yzwy
    mul r5.yzw, r5.yyzw, cb1[3].zzzz
    mad r5.yzw, r5.yyzw, r3.xxxx, r7.xxyz
    mad r7.xyz, v7.yzwy, r1.xxxx, r2.xyzx
    dp3 r1.x, r7.xyzx, r7.xyzx
    rsq r1.x, r1.x
    mul r7.xyz, r1.xxxx, r7.xyzx
    dp3_sat r1.x, r2.xyzx, r7.xyzx
    mul r1.x, r3.x, r1.x
    mul r7.xyz, r4.xyzx, r1.xxxx
    mad r5.yzw, r7.xxyz, l(0.000000, 0.050000, 0.050000, 0.050000), r5.yyzw
    mul r7.xyz, r5.yzwy, v8.xyzx
    ieq r1.x, v11.x, l(3)
    mov r7.w, l(1.000000)
    mul r7.xyzw, r6.xyzw, r7.xyzw
    lt r2.w, r5.x, l(0.800000)
    lt r3.x, l(2.000000), cb1[3].x
    and r2.w, r2.w, r3.x
    if_nz r2.w
      mov r7.xyz, r1.yzwy
    endif 
    movc r6.xyzw, r1.xxxx, r7.xyzw, r6.xyzw
  endif 
  if_nz r3.y
    dp3 r1.x, v13.yzwy, v13.yzwy
    rsq r1.x, r1.x
    mul r1.yzw, r1.xxxx, v13.yyzw
    add r5.xyzw, -v6.xyzw, v17.xyzw
    dp4 r2.w, r5.xyzw, r5.xyzw
    sqrt r2.w, r2.w
    div r2.w, l(1.000000, 1.000000, 1.000000, 1.000000), r2.w
    lt r3.x, r2.w, l(0.100000)
    if_nz r3.x
      mov r3.x, l(1.000000)
    else 
      mul r3.x, r2.w, l(10.000000)
    endif 
    add r5.xyz, v5.xyzx, -v6.xyzx
    dp3 r2.w, r5.xyzx, r5.xyzx
    rsq r2.w, r2.w
    mul r5.xyz, r2.wwww, r5.xyzx
    dp3 r2.w, r1.yzwy, r2.xyzx
    mad r3.y, r2.w, l(0.500000), l(0.500000)
    mul r3.y, r3.x, r3.y
    dp3 r4.w, -r2.xyzx, r1.yzwy
    max r4.w, r4.w, l(0.000000)
    dp3 r1.y, -r5.xyzx, r1.yzwy
    mad r1.y, r1.y, l(0.500000), l(0.500000)
    mul r1.y, r1.y, cb1[3].x
    mad r1.y, cb1[3].x, r4.w, r1.y
    mul r1.y, r3.x, r1.y
    mul r1.yzw, r1.yyyy, cb1[2].xxyz
    mul r1.yzw, r0.wwww, r1.yyzw
    dp3 r4.w, r2.xyzx, r5.xyzx
    max r4.w, r4.w, l(0.000000)
    add r5.x, -r4.w, l(1.000000)
    mul r5.x, r5.x, r5.x
    max r2.w, r2.w, l(0.000000)
    mul r5.yzw, r4.xxyz, r2.wwww
    mul r5.xyz, r5.yzwy, r5.xxxx
    mad r7.xyz, r3.yyyy, r0.xyzx, r1.yzwy
    mul r5.xyz, r5.xyzx, cb1[3].zzzz
    mad r5.xyz, r5.xyzx, r3.xxxx, r7.xyzx
    mad r7.xyz, v13.yzwy, r1.xxxx, r2.xyzx
    dp3 r1.x, r7.xyzx, r7.xyzx
    rsq r1.x, r1.x
    mul r7.xyz, r1.xxxx, r7.xyzx
    dp3_sat r1.x, r2.xyzx, r7.xyzx
    mul r1.x, r3.x, r1.x
    mul r7.xyz, r4.xyzx, r1.xxxx
    mad r5.xyz, r7.xyzx, l(0.050000, 0.050000, 0.050000, 0.000000), r5.xyzx
    mul r5.xyz, r5.xyzx, v14.xyzx
    ieq r1.x, v16.y, l(3)
    mov r5.w, l(1.000000)
    mul r5.xyzw, r5.xyzw, r6.xyzw
    lt r2.w, r4.w, l(0.800000)
    lt r3.x, l(2.000000), cb1[3].x
    and r2.w, r2.w, r3.x
    if_nz r2.w
      mov r5.xyz, r1.yzwy
    endif 
    movc r6.xyzw, r1.xxxx, r5.xyzw, r6.xyzw
  endif 
  if_nz r3.z
    dp3 r1.x, v18.yzwy, v18.yzwy
    rsq r1.x, r1.x
    mul r1.yzw, r1.xxxx, v18.yyzw
    add r5.xyzw, -v6.xyzw, v22.xyzw
    dp4 r2.w, r5.xyzw, r5.xyzw
    sqrt r2.w, r2.w
    div r2.w, l(1.000000, 1.000000, 1.000000, 1.000000), r2.w
    lt r3.x, r2.w, l(0.100000)
    if_nz r3.x
      mov r3.x, l(1.000000)
    else 
      mul r3.x, r2.w, l(10.000000)
    endif 
    add r5.xyz, v5.xyzx, -v6.xyzx
    dp3 r2.w, r5.xyzx, r5.xyzx
    rsq r2.w, r2.w
    mul r5.xyz, r2.wwww, r5.xyzx
    dp3 r2.w, r1.yzwy, r2.xyzx
    mad r3.y, r2.w, l(0.500000), l(0.500000)
    mul r3.y, r3.x, r3.y
    dp3 r3.z, -r2.xyzx, r1.yzwy
    max r3.z, r3.z, l(0.000000)
    dp3 r1.y, -r5.xyzx, r1.yzwy
    mad r1.y, r1.y, l(0.500000), l(0.500000)
    mul r1.y, r1.y, cb1[3].x
    mad r1.y, cb1[3].x, r3.z, r1.y
    mul r1.y, r3.x, r1.y
    mul r1.yzw, r1.yyyy, cb1[2].xxyz
    mul r1.yzw, r0.wwww, r1.yyzw
    dp3 r3.z, r2.xyzx, r5.xyzx
    max r3.z, r3.z, l(0.000000)
    add r4.w, -r3.z, l(1.000000)
    mul r4.w, r4.w, r4.w
    max r2.w, r2.w, l(0.000000)
    mul r5.xyz, r4.xyzx, r2.wwww
    mul r5.xyz, r4.wwww, r5.xyzx
    mad r7.xyz, r3.yyyy, r0.xyzx, r1.yzwy
    mul r5.xyz, r5.xyzx, cb1[3].zzzz
    mad r5.xyz, r5.xyzx, r3.xxxx, r7.xyzx
    mad r7.xyz, v18.yzwy, r1.xxxx, r2.xyzx
    dp3 r1.x, r7.xyzx, r7.xyzx
    rsq r1.x, r1.x
    mul r7.xyz, r1.xxxx, r7.xyzx
    dp3_sat r1.x, r2.xyzx, r7.xyzx
    mul r1.x, r3.x, r1.x
    mul r7.xyz, r4.xyzx, r1.xxxx
    mad r5.xyz, r7.xyzx, l(0.050000, 0.050000, 0.050000, 0.000000), r5.xyzx
    mul r5.xyz, r5.xyzx, v19.xyzx
    ieq r1.x, v21.z, l(3)
    mov r5.w, l(1.000000)
    mul r5.xyzw, r5.xyzw, r6.xyzw
    lt r2.w, r3.z, l(0.800000)
    lt r3.x, l(2.000000), cb1[3].x
    and r2.w, r2.w, r3.x
    if_nz r2.w
      mov r5.xyz, r1.yzwy
    endif 
    movc r6.xyzw, r1.xxxx, r5.xyzw, r6.xyzw
  endif 
  if_nz r3.w
    dp3 r1.x, v23.yzwy, v23.yzwy
    rsq r1.x, r1.x
    mul r1.yzw, r1.xxxx, v23.yyzw
    add r3.xyzw, -v6.xyzw, v27.xyzw
    dp4 r2.w, r3.xyzw, r3.xyzw
    sqrt r2.w, r2.w
    div r2.w, l(1.000000, 1.000000, 1.000000, 1.000000), r2.w
    lt r3.x, r2.w, l(0.100000)
    if_nz r3.x
      mov r3.x, l(1.000000)
    else 
      mul r3.x, r2.w, l(10.000000)
    endif 
    add r3.yzw, v5.xxyz, -v6.xxyz
    dp3 r2.w, r3.yzwy, r3.yzwy
    rsq r2.w, r2.w
    mul r3.yzw, r2.wwww, r3.yyzw
    dp3 r2.w, r1.yzwy, r2.xyzx
    mad r4.w, r2.w, l(0.500000), l(0.500000)
    mul r4.w, r3.x, r4.w
    dp3 r5.x, -r2.xyzx, r1.yzwy
    max r5.x, r5.x, l(0.000000)
    dp3 r1.y, -r3.yzwy, r1.yzwy
    mad r1.y, r1.y, l(0.500000), l(0.500000)
    mul r1.y, r1.y, cb1[3].x
    mad r1.y, cb1[3].x, r5.x, r1.y
    mul r1.y, r3.x, r1.y
    mul r1.yzw, r1.yyyy, cb1[2].xxyz
    mul r1.yzw, r0.wwww, r1.yyzw
    dp3 r0.w, r2.xyzx, r3.yzwy
    max r0.w, r0.w, l(0.000000)
    add r3.y, -r0.w, l(1.000000)
    mul r3.y, r3.y, r3.y
    max r2.w, r2.w, l(0.000000)
    mul r5.xyz, r4.xyzx, r2.wwww
    mul r3.yzw, r3.yyyy, r5.xxyz
    mad r0.xyz, r4.wwww, r0.xyzx, r1.yzwy
    mul r3.yzw, r3.yyzw, cb1[3].zzzz
    mad r0.xyz, r3.yzwy, r3.xxxx, r0.xyzx
    mad r3.yzw, v23.yyzw, r1.xxxx, r2.xxyz
    dp3 r1.x, r3.yzwy, r3.yzwy
    rsq r1.x, r1.x
    mul r3.yzw, r1.xxxx, r3.yyzw
    dp3_sat r1.x, r2.xyzx, r3.yzwy
    mul r1.x, r3.x, r1.x
    mul r3.xyz, r4.xyzx, r1.xxxx
    mad r0.xyz, r3.xyzx, l(0.050000, 0.050000, 0.050000, 0.000000), r0.xyzx
    mul r3.xyz, r0.xyzx, v24.xyzx
    ieq r0.x, v26.w, l(3)
    mov r3.w, l(1.000000)
    mul r3.xyzw, r3.xyzw, r6.xyzw
    lt r0.y, r0.w, l(0.800000)
    lt r0.z, l(2.000000), cb1[3].x
    and r0.y, r0.z, r0.y
    if_nz r0.y
      mov r3.xyz, r1.yzwy
    endif 
    movc r6.xyzw, r0.xxxx, r3.xyzw, r6.xyzw
  endif 
endif 
mul r0.xyzw, r6.xyzw, l(0.500000, 0.500000, 0.500000, 0.500000)
movc r0.xyzw, cb2[6].yyyy, r0.xyzw, r6.xyzw
add r1.xyz, v5.xyzx, -v6.xyzx
dp3 r1.w, r1.xyzx, r1.xyzx
rsq r2.w, r1.w
mul r1.xyz, r1.xyzx, r2.wwww
dp3 r1.x, r1.xyzx, r2.xyzx
max r1.x, r1.x, l(0.000000)
lt r1.x, r1.x, cb2[0].w
movc r1.xyz, r1.xxxx, cb2[0].xyzx, r0.xyzx
movc r1.xyz, cb2[6].wwww, r1.xyzx, r0.xyzx
sqrt r1.w, r1.w
div r1.w, r1.w, cb2[1].w
add r2.xyz, r1.wwww, r1.xyzx
movc r0.xyz, cb2[7].zzzz, r2.xyzx, r1.xyzx
dp4 r1.x, r0.xyzw, cb2[2].xyzw
dp4 r1.y, r0.xyzw, cb2[3].xyzw
dp4 r1.z, r0.xyzw, cb2[4].xyzw
dp4 r1.w, r0.xyzw, cb2[5].xyzw
movc o0.xyzw, cb2[6].xxxx, r1.xyzw, r0.xyzw
ret 
// Approximately 1343 instruction slots used
